# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/ebd0ca55-ed84-4c93-5f62-25a94fbfbe4c/volume/rsync-recipes/libpng-1.6.37-on-osx, last modified Tue Apr 23 12:29:08 2019
# ------------------------------------------------

package:
    name: libpng
    version: 1.6.37
source:
    patches:
        - 0001-Include-pkg-config-files-in-the-Windows-packages-too.patch
    sha256: daeb2620d829575513e35fecc83f0d3791a620b9b93d800b763542ece9390fb4
    url: http://download.sourceforge.net/libpng/libpng-1.6.37.tar.gz
build:
    number: '0'
    run_exports:
        - libpng >=1.6.37,<1.7.0a0
    string: ha441bb4_0
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - automake 1.16.1 pl526_0
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libtool 2.4.6 h1de35cc_5
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - perl 5.26.2 h4e221da_0
    host:
        - zlib 1.2.11 h1de35cc_3
    run:
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libpng.a
        - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}
        - libpng-config --version
about:
    description: 'libpng is the official PNG reference library. It supports almost
        all PNG

        features, is extensible, and has been extensively tested for over 20 years.

        '
    dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
    doc_url: http://www.libpng.org/pub/png/libpng.html
    home: http://www.libpng.org/pub/png/libpng.html
    license: zlib/libpng
    license_file: LICENSE
    license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
    summary: PNG reference library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - pkgw
