# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/fsspec-0.7.4-on-linux_64, last modified Fri May 29 15:50:52 2020
# ------------------------------------------------

package:
    name: fsspec
    version: 0.7.4
source:
    fn: fsspec-0.7.4.tar.gz
    sha256: 7075fde6d617cd3a97eac633d230d868121a188a46d16a0dcb484eea0cf2b955
    url: https://pypi.io/packages/source/f/fsspec/fsspec-0.7.4.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/fsspec_1590767631718/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python  -m
        pip install . --no-deps --ignore-installed -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - jinja2 2.11.2 py_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - markupsafe 1.1.1 py38h7b6447c_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py38_3
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 46.4.0 py38_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
test:
    imports:
        - fsspec
about:
    home: https://github.com/martindurant/filesystem_spec
    license: BSD-3-Clause
    license_file: LICENSE
    summary: A specification for pythonic filesystems
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - TomAugspurger
        - martindurant
