# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: libllvm9
    version: 9.0.1
source:
    patches:
        - patches/amd-roc-2.7.0.diff
        - patches/intel-D47188-svml-VF.patch
        - patches/numba-0001-Revert-Limit-size-of-non-GlobalValue-name.patch
        - patches/numba-0001-Revert-NVPTX-Use-atomicrmw-fadd-instead-of-intrinsic.patch
        - patches/numba-0002-Revert-NVPTX-Remove-now-unused-atomic.load.add.f32-i.patch
    sha256: 00a1ee1f389f81e9979f3a640a01c431b3021de0d42278f6508391a2f0b81c9a
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/llvm-9.0.1.src.tar.xz
build:
    activate_in_script: true
    number: 1
    run_exports:
        - libllvm9 9.0.1 1
    string: h21ff451_1
requirements:
    build:
        - bzip2 1.0.8 h1de35cc_0
        - ca-certificates 2020.6.24 0
        - clang_bootstrap_osx-64 10.0.0 h05bbb7f_0
        - cmake 3.14.0 haff7e42_0
        - expat 2.2.9 hb1e8313_2
        - krb5 1.18.2 h75d18d8_0
        - libcurl 7.71.0 h8a08a2b_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 hb1e8313_2
        - libssh2 1.9.0 ha12b0ac_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - rhash 1.3.8 ha12b0ac_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    host:
        - libcxx 10.0.0 1
    run:
        - libcxx >=4.0.1
test:
    commands:
        - test -f $PREFIX/lib/libLLVM-9${SHLIB_EXT}
about:
    dev_url: https://github.com/llvm-mirror/llvm
    home: http://llvm.org/
    license: Apache-2.0 WITH LLVM-exception
    license_family: Apache
    license_file: LICENSE.TXT
    summary: Development headers and libraries for LLVM
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - inducer
        - isuruf
        - jakirkham
        - mingwandroid
        - timsnyder
