# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/b14d0463-d9ed-461e-6d6d-e845a67edccf/volume/rsync-recipes/mpfr-4.0.2-on-osx, last modified Thu Jun 25 15:00:42 2020
# ------------------------------------------------

package:
    name: mpfr
    version: 4.0.2
source:
    fn: mpfr-4.0.2.tar.bz2
    patches:
        - patches/build-vc14.patch
        - patches/corei5.patch
    sha256: ae26cace63a498f07047a784cd3b0e4d010b44d2b193bab82af693de57a19a78
    url: http://ftp.gnu.org/gnu/mpfr/mpfr-4.0.2.tar.gz
build:
    number: '1'
    run_exports:
        - mpfr >=4.0.2,<5.0a0
    string: h9066e36_1
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - libtool 2.4.6 h1de35cc_5
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - gmp 6.1.2 hb37e062_1
        - libcxx 10.0.0 1
    run:
        - gmp >=6.1.2
test:
    commands:
        - test -f ${PREFIX}/lib/libmpfr.a
        - test -f ${PREFIX}/lib/libmpfr${SHLIB_EXT}
    requires:
        - clang_osx-64 10.*
        - libtool
        - m4
about:
    home: http://www.mpfr.org/
    license: LGPL-3.0-only
    license_file: /opt/concourse/worker/volumes/live/b14d0463-d9ed-461e-6d6d-e845a67edccf/volume/mpfr_1593117303425/work/COPYING.LESSER
    summary: The MPFR library is a C library for multiple-precision floating-point
        computations with correct rounding.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
        - marcelotrevisani
