# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/de659a8a-f930-4bea-5f04-092e749abe88/volume/rsync-recipes/zope.interface-4.7.1-python_3.8-on-osx, last modified Thu Nov 21 17:40:09 2019
# ------------------------------------------------

package:
    name: zope.interface
    version: 4.7.1
source:
    sha256: 4bb937e998be9d5e345f486693e477ba79e4344674484001a0b646be1d530487
    url: https://pypi.io/packages/source/z/zope.interface/zope.interface-4.7.1.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/de659a8a-f930-4bea-5f04-092e749abe88/volume/zope.interface_1574379948916/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38h1de35cc_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
        - zope 1.0 py38_1
    run:
        - python >=3.8,<3.9.0a0
        - zope
test:
    imports:
        - zope
        - zope.interface
        - zope.interface._zope_interface_coptimizations
        - zope.interface.common
        - zope.interface.common.mapping
        - zope.interface.common.tests
        - zope.interface.tests
about:
    description: 'Provides an implementation of object interfaces for Python.Interfaces
        are objects

        that specify the external behavior of objects that provide them.

        '
    dev_url: https://github.com/zopefoundation/zope.interface
    doc_source_url: https://github.com/zopefoundation/zope.interface//blob/master/docs/index.rst
    doc_url: http://docs.zope.org/zope.interface/
    home: http://docs.zope.org/zope.interface/
    license: ZPL 2.1
    license_family: Other
    license_file: LICENSE.txt
    summary: Interfaces for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - ocefpaf
