# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/d105c0fb-554a-4222-6575-fb0a785336d7/volume/rsync-recipes/pytables-3.6.1-python_3.8-on-osx, last modified Tue Jan 28 16:34:11 2020
# ------------------------------------------------

package:
    name: pytables
    version: 3.6.1
source:
    sha256: 49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49
    url: https://pypi.io/packages/source/t/tables/tables-3.6.1.tar.gz
build:
    entry_points:
        - pt2to3 = tables.scripts.pt2to3:main
        - ptdump = tables.scripts.ptdump:main
        - ptrepack = tables.scripts.ptrepack:main
        - pttree = tables.scripts.pttree:main
    number: '0'
    string: py38h4727e94_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - blas 1.0 mkl
        - blosc 1.16.3 hd9629dc_0
        - bzip2 1.0.8 h1de35cc_0
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - cython 0.29.14 py38h0a44026_0
        - hdf5 1.10.4 hfa1e0ec_0
        - intel-openmp 2019.4 233
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - lz4-c 1.8.1.2 h1de35cc_0
        - lzo 2.10 h362108e_2
        - mkl 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - mkl_fft 1.0.15 py38h5e564d8_0
        - mkl_random 1.1.0 py38h6440ff4_0
        - ncurses 6.1 h0a44026_1
        - numexpr 2.7.0 py38h27c97d8_0
        - numpy 1.14.6 py38h5fd8802_4
        - numpy-base 1.14.6 py38h6575580_4
        - openssl 1.1.1d h1de35cc_3
        - pip 20.0.2 py38_0
        - python 3.8.1 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 45.1.0 py38_0
        - six 1.14.0 py38_0
        - snappy 1.1.7 he62c110_3
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
        - zstd 1.3.7 h5bba6e5_0
    run:
        - blosc >=1.16.3,<2.0a0
        - bzip2 >=1.0.8,<2.0a0
        - hdf5 >=1.10.4,<1.10.5.0a0
        - libcxx >=4.0.1
        - lzo >=2.10,<3.0a0
        - mock
        - numexpr
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
        - six
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - pt2to3 -h
        - ptdump -h
        - ptrepack -h
        - pttree -h
    requires:
        - mock
        - setuptools
about:
    description: 'PyTables is a package for managing hierarchical datasets and designed
        to

        efficiently and easily cope with extremely large amounts of data. PyTables

        is built on top of the HDF5 library, using the Python language and the

        NumPy package.

        '
    dev_url: https://github.com/PyTables
    doc_url: http://www.pytables.org/
    home: http://www.pytables.org
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Brings together Python, HDF5 and NumPy to easily handle large amounts
        of data.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - scopatz
        - tomkooij
