# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/cc0ee7bb-1065-44c4-5867-0fd5d13729e0/volume/rsync-recipes/watchdog-0.10.3-python_3.8-on-osx, last modified Mon Jun 29 11:13:30 2020
# ------------------------------------------------

package:
    name: watchdog
    version: 0.10.3
source:
    fn: watchdog-0.10.3.tar.gz
    sha256: 4214e1379d128b0588021880ccaf40317ee156d4603ac388b9adcf29165e0c04
    url: https://pypi.io/packages/source/w/watchdog/watchdog-0.10.3.tar.gz
build:
    entry_points:
        - watchmedo = watchdog.watchmedo:main
    number: '0'
    script: /opt/concourse/worker/volumes/live/cc0ee7bb-1065-44c4-5867-0fd5d13729e0/volume/watchdog_1593447373245/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps -vv
    string: py38haf1e3a3_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 h0a44026_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - argh >=0.24.1
        - pathtools >=0.1.1
        - python >=3.8,<3.9.0a0
        - pyyaml >=3.10
test:
    commands:
        - python -m pip check
        - watchmedo --help
    imports:
        - _watchdog_fsevents
        - watchdog
        - watchdog.observers
        - watchdog.observers.fsevents
        - watchdog.tricks
        - watchdog.utils
    requires:
        - pip
about:
    doc_url: http://pythonhosted.org/watchdog
    home: http://github.com/gorakhargosh/watchdog
    license: Apache 2.0
    license_file: LICENSE
    summary: Filesystem events monitoring
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - andfoy
        - ccordoba12
        - goanpeca
        - rlaverde
