# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f6d4ee24-7c1f-4b99-79a5-3cad61560df7/volume/aggregate/multipledispatch-feedstock/recipe, last modified Mon Nov 11 05:13:12 2019
# ------------------------------------------------

package:
    name: multipledispatch
    version: 0.6.0
source:
    fn: multipledispatch-0.6.0.tar.gz
    sha256: a7ab1451fd0bf9b92cab3edbd7b205622fb767aeefb4fb536c2e3de9e0a38bea
    url: https://pypi.io/packages/source/m/multipledispatch/multipledispatch-0.6.0.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/f6d4ee24-7c1f-4b99-79a5-3cad61560df7/volume/multipledispatch_1573471310822/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - six 1.12.0 py38_1000
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
        - six
test:
    imports:
        - multipledispatch
about:
    description: 'This implementation of multiple dispatch is efficient, mostly complete,

        performs static analysis to avoid conflicts, and provides optional

        namespace support.

        '
    dev_url: https://github.com/mrocklin/multipledispatch/
    doc_source_url: https://github.com/mrocklin/multipledispatch/blob/master/docs/source/index.rst
    doc_url: https://multiple-dispatch.readthedocs.io
    home: https://github.com/mrocklin/multipledispatch/
    license: BSD 3-Clause
    license_family: BSD
    summary: Multiple dispatch in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
