# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Sep 15 15:02:17 2020
# ------------------------------------------------

package:
    name: conda
    version: 4.8.5
source:
    fn: conda-4.8.5.tar.gz
    patches:
        - gh9946_utf_16_replacement.patch
    sha256: d8dacb3696ba6b61337f2b354f0138dd2c9212d78a0dd98dea8e1fae01b4bf0e
    url: https://github.com/conda/conda/archive/4.8.5.tar.gz
build:
    always_include_files:
        - bin/activate
        - bin/conda
        - bin/deactivate
    number: '1'
    string: py38h32f6830_1
requirements:
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - conda-package-handling 1.7.0 py38h4d0b108_4
        - libcxx 10.0.1 h5f48129_0
        - libffi 3.2.1 hb1e8313_1007
        - ncurses 6.2 hb1e8313_1
        - openssl 1.1.1g haf1e3a3_1
        - pip 20.2.3 py_0
        - python 3.8.5 hfc71d35_7_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 h0678c8f_2
        - ruamel_yaml 0.15.80 py38h4d0b108_1002
        - setuptools 49.6.0 py38h32f6830_0
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.33.0 h960bd1c_0
        - tk 8.6.10 hb0a8c7a_0
        - tqdm 4.49.0 pyh9f0ad1d_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 haf1e3a3_1
        - yaml 0.2.5 haf1e3a3_0
        - zlib 1.2.11 h7795811_1009
    run:
        - conda-package-handling >=1.3.0
        - pycosat >=0.6.3
        - pyopenssl >=16.2.0
        - python >=3.8,<3.9.0a0
        - python_abi 3.8.* *_cp38
        - requests >=2.18.4,<3
        - ruamel_yaml >=0.11.14,<0.16
        - setuptools >=31.0.1
    run_constrained:
        - conda-build >=3
        - conda-env >=2.6
        - cytoolz >=0.8.1
test:
    commands:
        - unset CONDA_SHLVL
        - eval "$(python -m conda shell.bash hook)"
        - conda activate base
        - export PYTHON_MAJOR_VERSION=$(python -c "import sys; print(sys.version_info[0])")
        - export TEST_PLATFORM=$(python -c "import sys; print('win' if sys.platform.startswith('win')
            else 'unix')")
        - export PYTHONHASHSEED=$(python -c "import random as r; print(r.randint(0,4294967296))")
            && echo "PYTHONHASHSEED=$PYTHONHASHSEED"
        - env | sort
        - conda info
        - conda create -y -p ./built-conda-test-env
        - conda activate ./built-conda-test-env
        - echo $CONDA_PREFIX
        - '[ "$CONDA_PREFIX" = "$PWD/built-conda-test-env" ] || exit 1'
        - conda deactivate
    files:
        - test_conda.sh
    imports:
        - conda
        - conda_env
    requires:
        - mock
        - pexpect
        - pytest
        - responses
    source_files:
        - conftest.py
        - setup.cfg
        - tests
about:
    description: 'Conda is an open source package management system and environment
        management system for installing multiple versions of software packages and
        their dependencies and switching easily between them. It works on Linux, OS
        X and Windows, and was created for Python programs but can package and distribute
        any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: https://conda.io/projects/conda/en/latest/
    home: https://conda.io
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - kalefranz
        - mbargull
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
