# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/38a82656-7799-451c-584b-c86ea5775a89/volume/aggregate/sphinxcontrib-feedstock/recipe, last modified Wed Nov 13 10:22:56 2019
# ------------------------------------------------

package:
    name: sphinxcontrib
    version: '1.0'
build:
    number: '1'
    string: py38_1
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - sphinxcontrib
about:
    license: BSD
    summary: Python namespace for sphinxcontrib
extra:
    copy_test_source_files: true
    final: true
