# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/0c260908-b027-46e4-4574-ccd809c87d59/volume/aggregate/ipython_genutils-feedstock/recipe, last modified Wed Oct 30 07:18:34 2019
# ------------------------------------------------

package:
    name: ipython_genutils
    version: 0.2.0
source:
    fn: ipython_genutils-0.2.0.tar.gz
    sha256: eb2e116e75ecef9d4d228fdc66af54269afa26ab4463042e33785b887c628ba8
    url: https://pypi.io/packages/source/i/ipython_genutils/ipython_genutils-0.2.0.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_0
        - readline 7.0 h1de35cc_5
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - ipython_genutils
        - ipython_genutils.testing
        - ipython_genutils.tests
about:
    description: 'General purpose utilities.

        '
    home: http://ipython.org
    license: BSD 3-Clause
    license_file: COPYING.md
    summary: vestigial utilities from IPython
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - minrk
        - msarahan
        - pelson
        - scopatz
        - takluyver
