# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/e8358963-4a9a-4a7c-7dfa-2943f30ec631/volume/rsync-recipes/ca-certificates-2020.6.24-on-osx, last modified Mon Jun 29 11:08:27 2020
# ------------------------------------------------

package:
    name: ca-certificates
    version: 2020.6.24
source:
    fn: cacert.pem
    sha256: 726889705b00f736200ed7999f7a50021b8735d53228d679c4e6665aa3b44987
    url: https://curl.haxx.se/ca/cacert-2020-06-24.pem
build:
    commands:
        - /usr/bin/curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
        - /usr/bin/openssl -CAfile "${PREFIX}/ssl/cacert.pem" -CApath nosuchdir s_client
            -showcerts -connect www.google.com:443
        - test -f "${PREFIX}/ssl/cacert.pem"
        - test -f "${PREFIX}/ssl/cert.pem"
    number: '0'
    string: '0'
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: MPL 2.0
    license_file: LICENSE.txt
    summary: Certificates for use with other packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
