# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/47a3ec7c-70dc-43c0-7317-def24a8afaf5/volume/rsync-recipes/scikit-learn-0.23.1-python_3.8-blas_impl_mkl-on-osx, last modified Thu Jun 18 11:10:03 2020
# ------------------------------------------------

package:
    name: scikit-learn
    version: 0.23.1
source:
    sha256: 3596ede14e1edcfee2e10ecf2a52cd10b2df3f8b763fe14d6e99141e6ca5ecba
    url: https://github.com/scikit-learn/scikit-learn/archive/0.23.1.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .  --verbose
    string: py38h603561c_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py38_0
        - cython 0.29.20 py38hb1e8313_0
        - intel-openmp 2019.4 233
        - joblib 0.15.1 py_0
        - libcxx 10.0.0 1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - libgfortran 3.0.1 h93005f0_2
        - llvm-openmp 10.0.0 h28b9765_0
        - mkl 2019.4 233
        - mkl-devel 2019.4 233
        - mkl-include 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - mkl_fft 1.1.0 py38hc64f4ea_0
        - mkl_random 1.1.1 py38h959d312_0
        - ncurses 6.2 h0a44026_1
        - numpy 1.14.6 py38h5fd8802_4
        - numpy-base 1.14.6 py38h6575580_4
        - numpy-devel 1.14.6 py38h4ba5984_4
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - scipy 1.3.1 py38h1410ff5_0
        - setuptools 47.3.0 py38_0
        - six 1.15.0 py_0
        - sqlite 3.31.1 h5c1f38d_1
        - threadpoolctl 2.1.0 pyh5ca1d4c_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - blas 1.0 mkl
        - joblib >=0.11
        - libcxx >=10.0.0
        - llvm-openmp >=10.0.0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
        - scipy
        - threadpoolctl
test:
    commands:
        - export OPENBLAS_NUM_THREADS=1
        - export OMP_NUM_THREADS=1
        - pytest --timeout 300 -n 1 --verbose --pyargs sklearn -k "not (_not_a_real_test
            or network)"
    imports:
        - sklearn
    requires:
        - cython >=0.28.5
        - pytest >=3.3.0
        - pytest-timeout
        - pytest-xdist
about:
    home: http://scikit-learn.org/
    license: BSD-3-Clause
    license_file: COPYING
    summary: A set of python modules for machine learning and data mining
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - adrinjalali
        - amueller
        - astaric
        - jakirkham
        - jnothman
        - lesteve
        - msarahan
        - ocefpaf
        - ogrisel
        - rth
