# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/5bfdfc6b-de5a-4470-7e2d-67cb257afd23/volume/rsync-recipes/widgetsnbextension-3.5.1-python_3.8-on-osx, last modified Wed Aug 21 10:43:09 2019
# ------------------------------------------------

package:
    name: widgetsnbextension
    version: 3.5.1
source:
    sha256: 079f87d87270bce047512400efd70238820751a11d2d8cb137a5a5bdbaf255c7
    url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-3.5.1.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/5bfdfc6b-de5a-4470-7e2d-67cb257afd23/volume/widgetsnbextension_1580237066981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_0
requirements:
    host:
        - appnope 0.1.0 py38_0
        - attrs 19.3.0 py_0
        - backcall 0.1.0 py38_0
        - bleach 3.1.0 py_0
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - decorator 4.4.1 py_0
        - defusedxml 0.6.0 py_0
        - entrypoints 0.3 py38_0
        - importlib_metadata 1.4.0 py38_0
        - ipykernel 5.1.4 py38h39e3cac_0
        - ipython 7.11.1 py38h39e3cac_0
        - ipython_genutils 0.2.0 py38_0
        - jedi 0.16.0 py38_0
        - jinja2 2.10.3 py_0
        - jsonschema 3.2.0 py38_0
        - jupyter_client 5.3.4 py38_0
        - jupyter_core 4.6.1 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - libsodium 1.0.16 h3efe00b_0
        - markupsafe 1.1.1 py38h1de35cc_0
        - mistune 0.8.4 py38h1de35cc_1000
        - more-itertools 8.0.2 py_0
        - nbconvert 5.6.1 py38_0
        - nbformat 5.0.4 py_0
        - ncurses 6.1 h0a44026_1
        - notebook 6.0.3 py38_0
        - openssl 1.1.1d h1de35cc_3
        - pandoc 2.2.3.2 0
        - pandocfilters 1.4.2 py38_1
        - parso 0.6.0 py_0
        - pexpect 4.8.0 py38_0
        - pickleshare 0.7.5 py38_1000
        - pip 20.0.2 py38_0
        - prometheus_client 0.7.1 py_0
        - prompt_toolkit 3.0.2 py_0
        - ptyprocess 0.6.0 py38_0
        - pygments 2.5.2 py_0
        - pyrsistent 0.15.7 py38h1de35cc_0
        - python 3.8.1 h359304d_1
        - python-dateutil 2.8.1 py_0
        - pyzmq 18.1.0 py38h0a44026_0
        - readline 7.0 h1de35cc_5
        - send2trash 1.5.0 py38_0
        - setuptools 45.1.0 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - terminado 0.8.3 py38_0
        - testpath 0.4.4 py_0
        - tk 8.6.8 ha441bb4_0
        - tornado 6.0.3 py38h1de35cc_0
        - traitlets 4.3.3 py38_0
        - wcwidth 0.1.7 py38_0
        - webencodings 0.5.1 py38_1
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zeromq 4.3.1 h0a44026_3
        - zipp 0.6.0 py_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - notebook >=4.4.1
        - python >=3.8,<3.9.0a0
test:
    imports:
        - widgetsnbextension
about:
    description: 'Interactive HTML widgets for Jupyter notebooks.

        '
    dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/master/widgetsnbextension
    doc_url: https://pypi.python.org/pypi/widgetsnbextension
    home: http://ipython.org
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE
    summary: Interactive Widgets for Jupyter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - jakirkham
        - jasongrout
        - minrk
        - ocefpaf
        - pbugnion
        - pelson
        - willingc
