# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/0ca279d0-0a52-4a6b-77a8-02fb7a0d6a62/volume/rsync-recipes/astropy-4.0.1.post1-python_3.8-on-osx, last modified Thu May 14 12:59:28 2020
# ------------------------------------------------

package:
    name: astropy
    version: 4.0.1.post1
source:
    sha256: 5c304a6c1845ca426e7bc319412b0363fccb4928cb4ba59298acd1918eec44b5
    url: https://pypi.io/packages/source/a/astropy/astropy-4.0.1.post1.tar.gz
build:
    detect_binary_files_with_prefix: false
    entry_points:
        - fits2bitmap = astropy.visualization.scripts.fits2bitmap:main
        - fitscheck = astropy.io.fits.scripts.fitscheck:main
        - fitsdiff = astropy.io.fits.scripts.fitsdiff:main
        - fitsheader = astropy.io.fits.scripts.fitsheader:main
        - fitsinfo = astropy.io.fits.scripts.fitsinfo:main
        - samp_hub = astropy.samp.hub_script:hub_script
        - volint = astropy.io.votable.volint:main
        - wcslint = astropy.wcs.wcslint:main
    number: '1'
    string: py38h01d97ff_1
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - intel-openmp 2019.4 233
        - libcxx 10.0.0 1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - mkl_fft 1.0.15 py38h5e564d8_0
        - mkl_random 1.1.0 py38h6440ff4_0
        - ncurses 6.2 h0a44026_1
        - numpy 1.16.6 py38h81c90fd_0
        - numpy-base 1.16.6 py38h6575580_0
        - openssl 1.1.1g h1de35cc_0
        - pip 20.0.2 py38_3
        - python 3.8.2 hf48f09d_13
        - readline 8.0 h1de35cc_0
        - setuptools 46.2.0 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - numpy >=1.16.6,<2.0a0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - fits2bitmap --help
        - fitscheck --help
        - fitsdiff --help
        - fitsheader --help
        - fitsinfo --help
        - samp_hub --help
        - volint --help
        - wcslint --help
    imports:
        - astropy
    requires:
        - pytest-astropy
about:
    description: 'The Astropy Project is a community effort to develop a single package
        for

        Astronomy in Python. It contains core functionality and common tools

        needed for performing astronomy and astrophysics research with Python.

        '
    dev_url: https://github.com/astropy/astropy
    doc_url: http://docs.astropy.org/en/stable/
    home: http://www.astropy.org/
    license: BSD-3-Clause
    license_file: LICENSE.rst
    summary: Community-developed Python Library for Astronomy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog-conda-forge
        - bsipocz
        - mwcraig
