# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/29c500db-6cdf-4cc7-7df8-fca74d6f0b64/volume/pull-recipes-asn1crypto/recipe, last modified Thu Jul  9 18:58:35 2020
# ------------------------------------------------

package:
    name: asn1crypto
    version: 1.3.0
source:
    sha256: 5a215cb8dc12f892244e3a113fe05397ee23c5c4ca7a69cd6e69811755efc42d
    url: https://pypi.io/packages/source/a/asn1crypto/asn1crypto-1.3.0.tar.gz
build:
    number: '1'
    script: /opt/concourse/worker/volumes/live/29c500db-6cdf-4cc7-7df8-fca74d6f0b64/volume/asn1crypto_1594339172552/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_1
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - asn1crypto
about:
    home: https://github.com/wbond/asn1crypto
    license: MIT
    license_file: LICENSE
    summary: Python ASN.1 library with a focus on performance and a pythonic API
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
        - ocefpaf
