# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/55b5588a-2735-42c5-69ae-b3bbe1b3648c/volume/rsync-recipes/pyrsistent-0.16.0-python_3.8-on-osx, last modified Mon Mar 30 12:01:51 2020
# ------------------------------------------------

package:
    name: pyrsistent
    version: 0.16.0
source:
    sha256: 28669905fe725965daa16184933676547c5bb40a5153055a8dee2a4bd7933ad3
    url: https://pypi.io/packages/source/p/pyrsistent/pyrsistent-0.16.0.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/55b5588a-2735-42c5-69ae-b3bbe1b3648c/volume/pyrsistent_1585587934441/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed -vvv
    string: py38h1de35cc_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - attrs 19.3.0 py_0
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - more-itertools 8.2.0 py_0
        - ncurses 6.2 h0a44026_0
        - openssl 1.1.1e h1de35cc_0
        - packaging 20.3 py_0
        - pip 20.0.2 py38_1
        - pluggy 0.13.1 py38_0
        - py 1.8.1 py_0
        - pyparsing 2.4.6 py_0
        - pytest 5.4.1 py38_0
        - pytest-runner 5.2 py_0
        - python 3.8.2 hc70fcce_0
        - readline 8.0 h1de35cc_0
        - setuptools 46.1.1 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.31.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wcwidth 0.1.9 py_0
        - wheel 0.34.2 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
        - six
test:
    imports:
        - pyrsistent
    requires:
        - hypothesis
        - pytest
about:
    home: http://github.com/tobgu/pyrsistent/
    license: MIT
    license_family: MIT
    license_file: LICENCE.mit
    summary: Persistent/Functional/Immutable data structures
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
