# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/6b5dfc3f-6535-4b1b-6dc6-275d26fb6e1d/volume/rsync-recipes/mkl_random-1.1.1-python_3.8-on-osx, last modified Tue May 26 17:10:10 2020
# ------------------------------------------------

package:
    name: mkl_random
    version: 1.1.1
source:
    sha256: e57d2d57e2796f408fd64fd723bf14259537965af50dd92be049417edfba8816
    url: https://github.com/IntelPython/mkl_random/archive/v1.1.1.tar.gz
build:
    ignore_run_exports:
        - blas
    number: '0'
    script: /opt/concourse/worker/volumes/live/6b5dfc3f-6535-4b1b-6dc6-275d26fb6e1d/volume/mkl_random_1590533915325/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py38h959d312_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - cython 0.29.17 py38h0a44026_0
        - intel-openmp 2019.4 233
        - libcxx 10.0.0 1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.4 233
        - mkl-devel 2019.4 233
        - mkl-include 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - ncurses 6.2 h0a44026_1
        - numpy-base 1.14.6 py38h6575580_4
        - openssl 1.1.1g h1de35cc_0
        - pip 20.0.2 py38_3
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 46.4.0 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcxx >=10.0.0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.14,<2.0a0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - nosetests -v mkl_random
    imports:
        - mkl_random
        - mkl_random.mklrand
    requires:
        - nose
about:
    description: NumPy-based implementation of random number generation sampling using
        Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices
        of sampling algorithms available in MKL.
    home: http://github.com/IntelPython/mkl_random
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Intel (R) MKL-powered package for sampling from common probability distributions
        into NumPy arrays.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - oleksandr-pavlyk
