# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zipp-3.1.0-on-linux_64, last modified Thu Apr 30 16:47:02 2020
# ------------------------------------------------

package:
    name: zipp
    version: 3.1.0
source:
    patches:
        - use-scm-version.patch
    sha256: c599e4d75c98f6798c509911d08a22e6c021d074469042177c8c86fb92eefd96
    url: https://pypi.io/packages/source/z/zipp/zipp-3.1.0.tar.gz
build:
    noarch: python
    number: '0'
    script: '/tmp/build/80754af9/zipp_1588267477672/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps --ignore-installed -vv '
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py38_1
        - python 3.8.2 hcf32534_0
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py38_0
        - setuptools-scm 3.5.0 py_1
        - setuptools_scm 3.5.0 1
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - toml 0.10.0 pyh91ea838_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.6
test:
    commands:
        - python -m unittest test_zipp.py
        - pip check
    imports:
        - zipp
    requires:
        - func_timeout
        - importlib_metadata
        - jaraco.itertools
        - pip
    source_files:
        - test_zipp.py
about:
    dev_url: https://github.com/jaraco/zipp
    doc_url: https://zipp.readthedocs.io/en/latest
    home: https://github.com/jaraco/zipp
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A pathlib-compatible Zipfile object wrapper
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
