# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/6158b663-a4ca-4e19-7e05-8807e4f79146/volume/rsync-recipes/cython-0.29.21-python_3.8-on-osx, last modified Wed Jul 15 12:24:23 2020
# ------------------------------------------------

package:
    name: cython
    version: 0.29.21
source:
    sha256: e57acb89bd55943c8d8bf813763d20b9099cc7165c0f16b707631a7654be9cad
    url: https://pypi.io/packages/source/C/Cython/Cython-0.29.21.tar.gz
build:
    entry_points:
        - cygdb = Cython.Debugger.Cygdb:main
        - cython = Cython.Compiler.Main:setuptools_main
        - cythonize = Cython.Build.Cythonize:main
    number: '0'
    script: /opt/concourse/worker/volumes/live/6158b663-a4ca-4e19-7e05-8807e4f79146/volume/cython_1594835048880/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps -vv
    string: py38hb1e8313_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_1
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_1
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - setuptools 49.2.0 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcxx >=10.0.0
        - python >=3.8,<3.9.0a0
        - setuptools
test:
    commands:
        - cython --version
    files:
        - fib.pyx
    requires:
        - clang_osx-64 10.*
about:
    description: 'Cython is an optimising static compiler for both the Python programming

        language and the extended Cython programming language. It makes writing C

        extensions for Python as easy as Python itself.

        '
    dev_url: https://github.com/cython/cython
    doc_url: http://cython.org/#documentation
    home: http://www.cython.org/
    license: Apache-2.0
    license_file: LICENSE.txt
    summary: The Cython compiler for writing C extensions for the Python language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
        - scopatz
        - synapticarbors
