# This file created by conda-build 3.17.8
# ------------------------------------------------

package:
    name: importlib_metadata
    version: 1.7.0
source:
    sha256: 90bb658cdbbf6d1735b6341ce708fc7024a3e14e99ffdc5783edea9f9b077f83
    url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-1.7.0.tar.gz
build:
    noarch: generic
    number: 0
    string: '0'
requirements:
    run:
        - importlib-metadata >=1.7.0,<1.7.1.0a0
test:
    imports:
        - importlib_metadata
about:
    home: https://gitlab.com/python-devs/importlib_metadata
    license: Apache-2.0
    license_family: APACHE
    license_file: LICENSE
    summary: A library to access the metadata for a Python package
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
        - nicoddemus
