# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/78006c60-e55f-4a25-7a31-a7428907a661/volume/aggregate/backports.shutil_get_terminal_size-feedstock/recipe, last modified Thu Nov 14 10:30:01 2019
# ------------------------------------------------

package:
    name: backports.shutil_get_terminal_size
    version: 1.0.0
source:
    fn: backports.shutil_get_terminal_size-1.0.0.tar.gz
    sha256: 713e7a8228ae80341c70586d1cc0a8caa5207346927e23d09dcbcaf18eadec80
    url: https://pypi.io/packages/source/b/backports.shutil_get_terminal_size/backports.shutil_get_terminal_size-1.0.0.tar.gz
build:
    number: '2'
    script: pip install --no-deps .
    string: py38_2
requirements:
    host:
        - backports 1.0 py_2
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - backports
        - python >=3.8,<3.9.0a0
test:
    imports:
        - backports
        - backports.shutil_get_terminal_size
about:
    home: https://github.com/chrippa/backports.shutil_get_terminal_size
    license: MIT
    license_file: LICENSE
    summary: A backport of the get_terminal_size function from Python 3.3's shutil.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
