# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f291dbf9-128b-40bd-6bdc-e60664e6b355/volume/aggregate/zope.event-feedstock/recipe, last modified Tue Nov 19 03:25:57 2019
# ------------------------------------------------

package:
    name: zope.event
    version: '4.4'
source:
    fn: zope.event-4.4.tar.gz
    sha256: 69c27debad9bdacd9ce9b735dad382142281ac770c4a432b533d6d65c4614bcf
    url: https://pypi.io/packages/source/z/zope.event/zope.event-4.4.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
        - setuptools
test:
    imports:
        - zope
        - zope.event
about:
    description: 'This package provides a simple event system on which application-specific

        event systems can be built. For example, a type-based event dispatching

        system that builds on zope.interface can be found in zope.component. A

        simpler system is distributed with this package and is described in

        Class-based event handlers.

        '
    dev_url: http://github.com/zopefoundation/zope.event
    doc_url: http://zopeevent.readthedocs.io/en/latest/
    home: http://www.zope.org/en/latest/
    license: Zope Public License
    license_family: OTHER
    summary: Very basic event publishing system
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
