# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/43c7e547-ec03-48d4-5738-b986229f8cc3/volume/aggregate/cycler-feedstock/recipe, last modified Thu Nov 14 08:22:03 2019
# ------------------------------------------------

package:
    name: cycler
    version: 0.10.0
source:
    fn: cycler-v0.10.0.tar.gz
    sha256: b6d217635e03024196225367b1a438996dbbf0271bec488f00584f0e7dc15cfa
    url: https://github.com/matplotlib/cycler/archive/v0.10.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - six 1.13.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
        - six
test:
    imports:
        - cycler
about:
    description: 'Cycler is a package used to create composable style cycles.

        '
    dev_url: https://github.com/matplotlib/cycler
    doc_source_url: https://github.com/matplotlib/cycler/blob/master/doc/source/index.rst
    doc_url: http://matplotlib.org/cycler/
    home: http://matplotlib.org/cycler
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Composable style cycles.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - janschulz
        - ocefpaf
        - pelson
        - tacaswell
