# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/01a17f3d-eafe-4806-57a1-4b9ef5d1815f/volume/rsync-recipes/wurlitzer-2.0.1-python_3.8-on-osx, last modified Tue Jul 14 14:09:03 2020
# ------------------------------------------------

package:
    name: wurlitzer
    version: 2.0.1
source:
    sha256: d08f0728a998441aac3d7a0f8cd6dfed2ba2525144878fb49599b719085b7543
    url: https://pypi.io/packages/source/w/wurlitzer/wurlitzer-2.0.1.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py38_0
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - setuptools 49.1.0 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - wurlitzer
about:
    home: https://github.com/minrk/wurlitzer
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Capture C-level stdout/stderr in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - bjodah
        - minrk
