# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/11ffe144-d423-4f81-56c8-24085aded71c/volume/rsync-recipes/sqlite-3.32.3-on-osx, last modified Mon Jun 22 12:23:47 2020
# ------------------------------------------------

package:
    name: sqlite
    version: 3.32.3
source:
    -   folder: amalgamated
        patches:
            - patches/applicable-to-amalgamated/0001-expose_symbols.patch
        sha256: a31507123c1c2e3a210afec19525fd7b5bb1e19a6a34ae5b998fbd7302568b66
        url: https://www.sqlite.org/2020/sqlite-autoconf-3320300.tar.gz
build:
    number: '0'
    run_exports:
        - sqlite >=3.32.3,<4.0a0
    string: hffcf06c_0
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - libtool 2.4.6 h1de35cc_5
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - patch 2.7.6 h1de35cc_1001
        - perl 5.26.2 h4e221da_0
        - tapi 1000.10.8 ha1b3eb9_0
        - tk 8.6.10 hb0a8c7a_0
        - zlib 1.2.11 h1de35cc_3
    host:
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - ncurses 6.2 h0a44026_1
        - zlib 1.2.11 h1de35cc_3
    run:
        - libedit >=3.1.20191231,<3.2.0a0
        - ncurses >=6.2,<7.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - sqlite3 --version
        - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
        - test -f $PREFIX/include/sqlite3.h
about:
    description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

        public-domain, SQL database engine.It is the most used database engine

        in the world.

        '
    dev_url: https://github.com/mackyle/sqlite
    doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
    doc_url: http://www.sqlite.org/docs.html
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    license_url: http://www.sqlite.org/copyright.html
    summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - snorfalorpagus
