# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/82c9b088-8c6a-408a-74ae-bcaf5aa49aff/volume/rsync-recipes/libxml2-2.9.10-on-osx, last modified Fri Jun 12 12:01:07 2020
# ------------------------------------------------

package:
    name: libxml2
    version: 2.9.10
source:
    patches:
        - 0002-Make-and-install-a-pkg-config-file-on-Windows.patch
        - 0004-CVE-2017-8872.patch
    sha256: aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f
    url: http://xmlsoft.org/sources/libxml2-2.9.10.tar.gz
build:
    number: '1'
    run_exports:
        - libxml2 >=2.9.10,<2.10.0a0
    string: h3b9e6c8_1
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - automake 1.16.2 pl526_0
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libiconv 1.16 h1de35cc_0
        - libllvm10 10.0.0 h21ff451_0
        - libtool 2.4.6 h1de35cc_5
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - perl 5.26.2 h4e221da_0
        - pkg-config 0.29.2 h3efe00b_8
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - icu 58.2 h0a44026_3
        - libcxx 10.0.0 1
        - libiconv 1.16 h1de35cc_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - icu >=58.2,<59.0a0
        - libiconv >=1.16,<2.0a0
        - xz >=5.2.5,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - xmllint test.xml
        - conda inspect linkages -p $PREFIX libxml2
        - conda inspect objects -p $PREFIX libxml2
    files:
        - test.xml
about:
    description: 'Though libxml2 is written in C a variety of language

        bindings make it available in other environments.

        '
    dev_url: https://git.gnome.org/browse/libxml2/
    doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
    doc_url: http://xmlsoft.org/html/index.html
    home: http://xmlsoft.org/
    license: MIT
    license_family: MIT
    license_file: Copyright
    summary: The XML C parser and toolkit of Gnome
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chenghlee
        - gillins
        - jakirkham
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
        - scopatz
