# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/668d4048-91b2-4b42-5f2b-697e489a6a5f/volume/rsync-recipes/rtree-0.9.4-python_3.8-on-osx, last modified Sun May  3 18:30:29 2020
# ------------------------------------------------

package:
    name: rtree
    version: 0.9.4
source:
    sha256: cae327e2c03b3da4ea40d0fdf68f3e55fe9f302c56b9f31e1bfeb36dbea73f44
    url: https://pypi.io/packages/source/R/Rtree/Rtree-0.9.4.tar.gz
build:
    number: '1'
    script: /opt/concourse/worker/volumes/live/668d4048-91b2-4b42-5f2b-697e489a6a5f/volume/rtree_1588549625254/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py38_1
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h0a44026_6
        - libspatialindex 1.9.3 h0a44026_0
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.0.2 py38_1
        - python 3.8.2 hc70fcce_0
        - readline 8.0 h1de35cc_0
        - setuptools 46.1.3 py38_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libspatialindex >=1.9.3,<1.9.4.0a0
        - python >=3.8,<3.9.0a0
test:
    imports:
        - rtree
about:
    home: http://toblerity.github.com/rtree/
    license: MIT
    license_file: LICENSE.txt
    summary: R-Tree spatial index for Python GIS
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hobu
        - ocefpaf
