# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/44c7f931-5ccd-49e8-494d-1839d1bf3796/volume/rsync-recipes/pycurl-7.43.0.5-python_3.8-on-osx, last modified Tue Feb  4 10:40:28 2020
# ------------------------------------------------

package:
    name: pycurl
    version: 7.43.0.5
source:
    sha256: ec7dd291545842295b7b56c12c90ffad2976cc7070c98d7b1517b7b6cd5994b3
    url: https://pypi.io/packages/source/p/pycurl/pycurl-7.43.0.5.tar.gz
build:
    detect_binary_files_with_prefix: false
    number: '0'
    string: py38ha12b0ac_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - ca-certificates 2020.1.1 0
        - krb5 1.16.4 hddcf347_0
        - libcurl 7.67.0 h051b688_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - libssh2 1.8.2 ha12b0ac_0
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.1 h359304d_1
        - readline 7.0 h1de35cc_5
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcurl >=7.67.0,<8.0a0
        - openssl >=1.1.1d,<1.1.2a
        - python >=3.8,<3.9.0a0
test:
    imports:
        - curl
        - pycurl
about:
    description: 'PycURL is a Python interface to libcurl, the multiprotocol file
        transfer library.

        Similarly to the urllib Python module, PycURL can be used to fetch objects
        identified

        by a URL from a Python program.

        '
    dev_url: https://github.com/pycurl/pycurl
    doc_source_url: https://github.com/pycurl/pycurl/blob/master/doc/index.rst
    doc_url: http://pycurl.io/docs/latest/index.html
    home: http://pycurl.sourceforge.net/
    license: LGPL, MIT
    license_family: LGPL
    license_file: COPYING-LGPL
    summary: A Python Interface To The cURL library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chrisburr
