# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a3871457-b264-4197-7e6e-ab5e82525663/volume/aggregate/locket-feedstock/recipe, last modified Mon Nov 11 10:02:43 2019
# ------------------------------------------------

package:
    name: locket
    version: 0.2.0
source:
    fn: locket-0.2.0.tar.gz
    md5: fe870949c513d8f7079ba352463833ca
    url: https://pypi.io/packages/source/l/locket/locket-0.2.0.tar.gz
build:
    number: '1'
    script: python setup.py install
    string: py38_1
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - locket
about:
    description: 'Locket implements a lock that can be used by multiple processes
        provided

        they use the same path.

        '
    dev_url: https://github.com/mwilliamson/locket.py
    doc_source_url: https://github.com/mwilliamson/locket.py/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/locket
    home: https://github.com/mwilliamson/locket.py
    license: BSD 2-Clause
    license_file: LICENSE
    summary: File-based locks for Python for Linux and Windows
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jcrist
