# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/af2f842b-5b8b-4bb3-793c-9c4d49c17345/volume/rsync-recipes/numba-0.50.1-python_3.8-on-osx, last modified Sun Jul 12 13:21:51 2020
# ------------------------------------------------

package:
    name: numba
    version: 0.50.1
source:
    git_rev: 0.50.1
    git_url: https://github.com/numba/numba
build:
    entry_points:
        - numba = numba.misc.numba_entry:main
        - pycc = numba.pycc:main
    missing_dso_whitelist:
        - lib/libiomp5.dylib
    number: '1'
    script_env:
        - PY_VCRUNTIME_REDIST
    string: py38h959d312_1
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - intel-openmp 2020.1 216
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_1
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_1
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - intel-openmp 2019.4 233
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - libgfortran 3.0.1 h93005f0_2
        - libllvm9 9.0.1 h21ff451_1
        - llvm-openmp 10.0.0 h28b9765_0
        - llvmlite 0.33.0 py38ha11be7d_1
        - mkl 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - mkl_fft 1.1.0 py38hc64f4ea_0
        - mkl_random 1.1.1 py38h959d312_0
        - ncurses 6.2 h0a44026_1
        - numpy 1.14.6 py38h5fd8802_4
        - numpy-base 1.14.6 py38h6575580_4
        - openssl 1.1.1g h1de35cc_0
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - setuptools 49.1.0 py38_0
        - six 1.15.0 py_0
        - sqlite 3.32.3 hffcf06c_0
        - tbb 2020.0 h04f5b5a_0
        - tbb-devel 2020.0 h04f5b5a_0
        - tk 8.6.10 hb0a8c7a_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcxx >=10.0.0
        - llvm-openmp >=10.0.0
        - llvmlite >=0.33.0 *_1
        - llvmlite >=0.33.0,<0.34.0a0
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
        - setuptools
        - tbb >=2020.0
    run_constrained:
        - tbb >=2018.0.5
test:
    files:
        - mandel.py
    imports:
        - numba
        - numba.cext
        - numba.core
        - numba.core.annotations
        - numba.core.datamodel
        - numba.core.datamodel
        - numba.core.rewrites
        - numba.core.rewrites
        - numba.core.runtime
        - numba.core.runtime
        - numba.core.typeconv
        - numba.core.types
        - numba.core.typing
        - numba.core.typing
        - numba.core.unsafe
        - numba.core.unsafe
        - numba.cpython
        - numba.cpython.unsafe
        - numba.cuda
        - numba.cuda.cudadrv
        - numba.cuda.kernels
        - numba.cuda.simulator
        - numba.cuda.simulator.cudadrv
        - numba.cuda.tests
        - numba.cuda.tests.cudadrv
        - numba.cuda.tests.cudadrv.data
        - numba.cuda.tests.cudapy
        - numba.cuda.tests.cudasim
        - numba.cuda.tests.nocuda
        - numba.experimental
        - numba.experimental.jitclass
        - numba.misc
        - numba.misc.help
        - numba.np
        - numba.np.ufunc
        - numba.np.unsafe
        - numba.parfors
        - numba.pycc
        - numba.roc
        - numba.roc.hlc
        - numba.roc.hsadrv
        - numba.roc.servicelib
        - numba.roc.tests
        - numba.roc.tests.hsadrv
        - numba.roc.tests.hsapy
        - numba.scripts
        - numba.stencils
        - numba.testing
        - numba.tests
        - numba.tests.npyufunc
        - numba.tests.pycc_distutils_usecase
        - numba.tests.pycc_distutils_usecase.nested
        - numba.typed
        - numba.types
    requires:
        - cffi
        - clang_osx-64 10.*
        - clangxx_osx-64 10.*
        - intel-openmp
        - ipython
        - jinja2
        - numpy <1.18
        - pip
        - scipy
        - setuptools
        - tbb >=2018.0.5
about:
    description: 'Numba is an Open Source NumPy-aware optimizing compiler for Python

        sponsored by Anaconda, Inc. It uses the remarkable LLVM compiler

        infrastructure to compile Python syntax to machine code."

        '
    dev_url: https://github.com/numba/numba
    doc_url: http://numba.pydata.org/
    home: http://numba.github.com
    license: BSD 2-clause
    license_family: BSD
    license_file: LICENSE
    summary: NumPy aware dynamic Python compiler using LLVM
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - souravsingh
