# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a89ae5d9-4200-4f08-7083-6de90fdc229d/volume/aggregate/send2trash-feedstock/recipe, last modified Fri Nov  8 02:13:09 2019
# ------------------------------------------------

package:
    name: send2trash
    version: 1.5.0
source:
    fn: Send2Trash-1.5.0.tar.gz
    sha256: 60001cc07d707fe247c94f74ca6ac0d3255aabcb930529690897ca2a39db28b2
    url: https://pypi.io/packages/source/S/Send2Trash/Send2Trash-1.5.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    commands:
        - echo test > test.txt
        - python -c "from send2trash import *; send2trash('test.txt')"
    imports:
        - send2trash
about:
    home: https://github.com/hsoft/send2trash
    license: BSD-3-Clause
    license_family: BSD
    license_file: /opt/concourse/worker/volumes/live/a89ae5d9-4200-4f08-7083-6de90fdc229d/volume/aggregate/send2trash-feedstock/recipe/LICENSE
    summary: Python library to natively send files to Trash (or Recycle bin) on all
        platforms.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
