# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/7ca83760-8bf2-4927-7756-0687db6532bc/volume/rsync-recipes/libxslt-1.1.34-on-osx, last modified Fri Jun 12 13:57:00 2020
# ------------------------------------------------

package:
    name: libxslt
    version: 1.1.34
source:
    fn: libxslt-1.1.34.tar.gz
    patches:
        - 0002-win-profiler-config.patch
    sha256: 98b1bd46d6792925ad2dfe9a87452ea2adebf69dcb9919ffd55bf926a7f93f7f
    url: http://xmlsoft.org/sources/libxslt-1.1.34.tar.gz
build:
    number: '0'
    run_exports:
        - libxslt >=1.1.34,<2.0a0
    string: h83b36ba_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - make 4.2.1 h3efe00b_1
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - icu 58.2 h0a44026_3
        - libcxx 10.0.0 1
        - libiconv 1.16 h1de35cc_0
        - libxml2 2.9.10 h3b9e6c8_1
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - icu >=58.2,<59.0a0
        - libxml2 >=2.9.10,<2.10.0a0
test:
    commands:
        - xsltproc --version
        - conda inspect linkages -p $PREFIX libxslt
        - conda inspect objects -p $PREFIX libxslt
about:
    description: '"Libxslt is the XSLT C library developed for the GNOME project.

        XSLT itself is a an XML language to define transformation for XML.

        Libxslt is based on libxml2 the XML C library developed for the GNOME project.

        It also implements most of the EXSLT set of processor-portable extensions
        functions

        and some of Saxon''s evaluate and expressions extensions."

        '
    doc_source_url: https://github.com/GNOME/libxslt/tree/master/doc
    doc_url: http://xmlsoft.org/XSLT/
    home: http://xmlsoft.org/XSLT/
    license: MIT
    license_file: COPYING
    summary: The XSLT C library developed for the GNOME project
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chenghlee
        - ocefpaf
