# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/0068f992-3a72-47c6-4a10-a3714c9c0c34/volume/rsync-recipes/numexpr-2.7.1-blas_impl_mkl-python_3.8-on-osx, last modified Tue Feb  4 11:29:22 2020
# ------------------------------------------------

package:
    name: numexpr
    version: 2.7.1
source:
    sha256: b0d239d9827e1bcee08344fd05835823bc60aff97232e35a928214d03ff802b1
    url: https://pypi.io/packages/source/n/numexpr/numexpr-2.7.1.tar.gz
build:
    number: '0'
    script:
        - cp $PREFIX/site.cfg site.cfg
        - /opt/concourse/worker/volumes/live/0068f992-3a72-47c6-4a10-a3714c9c0c34/volume/numexpr_1580839183769/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
            -m pip install . --no-deps -vv
    string: py38hce01a72_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_0
        - intel-openmp 2019.4 233
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.4 233
        - mkl-devel 2019.4 233
        - mkl-include 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - ncurses 6.1 h0a44026_1
        - numpy-base 1.14.6 py38h6575580_4
        - numpy-devel 1.14.6 py38h4ba5984_4
        - openssl 1.1.1d h1de35cc_3
        - pip 20.0.2 py38_1
        - python 3.8.1 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 45.1.0 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.1 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - blas 1.0 mkl
        - libcxx >=4.0.1
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
test:
    imports:
        - numexpr
        - numexpr.interpreter
    requires:
        - setuptools
about:
    description: 'Numexpr is a fast numerical expression evaluator for NumPy. With
        it,

        expressions that operate on arrays (like "3*a+4*b") are accelerated and use

        less memory than doing the same calculation in Python.

        '
    dev_url: https://github.com/pydata/numexpr
    doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
    home: https://github.com/pydata/numexpr
    license: MIT
    license_file: LICENSE.txt
    summary: Fast numerical expression evaluator for NumPy.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - djkirkham
        - msarahan
        - ocefpaf
        - scopatz
