# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/ec09ac86-02be-4dd3-611c-f02ba14c21b5/volume/rsync-recipes/freetype-2.10.2-on-osx, last modified Thu Jun 18 14:07:59 2020
# ------------------------------------------------

package:
    name: freetype
    version: 2.10.2
source:
    patches:
        - 0003-Install-the-pkg-config-file-on-Windows-too.patch
    sha256: e09aa914e4f7a5d723ac381420949c55c0b90b15744adce5d1406046022186ab
    url: http://download.savannah.gnu.org/releases/freetype/freetype-2.10.2.tar.gz
build:
    number: '0'
    run_exports:
        - freetype >=2.10.2,<3.0a0
    string: ha233b18_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - make 4.2.1 h3efe00b_1
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - libpng 1.6.37 ha441bb4_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libpng >=1.6.37,<1.7.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - ${PREFIX}/bin/freetype-config --version
about:
    description: 'FreeType is designed to be small, efficient, highly customizable

        and portable while capable of producing high-quality output (glyph images)

        of most vector and bitmap font formats.

        '
    dev_url: http://git.savannah.gnu.org/cgit/freetype/
    doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
    doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
    home: https://www.freetype.org/
    license: GPL-2.0-only and LicenseRef-FreeType
    license_file:
        - docs/FTL.TXT
        - docs/GPLv2.TXT
    summary: A Free, High-Quality, and Portable Font Engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - msarahan
        - ocefpaf
