# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f79823e2-9e39-48fa-76ef-ee229e5f6355/volume/aggregate/ptyprocess-feedstock/recipe, last modified Wed Nov  6 05:42:30 2019
# ------------------------------------------------

package:
    name: ptyprocess
    version: 0.6.0
source:
    fn: ptyprocess-0.6.0.tar.gz
    sha256: 923f299cc5ad920c68f2bc0bc98b75b9f838b93b599941a6b63ddbc2476394c0
    url: https://pypi.io/packages/source/p/ptyprocess/ptyprocess-0.6.0.tar.gz
build:
    number: '0'
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_1
        - readline 7.0 h1de35cc_5
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - ptyprocess
about:
    description: 'Ptyprocess allows you to launch a subprocess in a pseudo terminal
        (pty),

        and interact with both the process and its pty.

        '
    dev_url: https://github.com/pexpect/ptyprocess
    doc_source_url: https://github.com/pexpect/ptyprocess/blob/master/docs/index.rst
    doc_url: http://ptyprocess.readthedocs.io/en/latest/
    home: https://github.com/pexpect/ptyprocess
    license: ISC
    summary: Run a subprocess in a pseudo terminal
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pelson
        - takluyver
