# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/2705da7e-52de-4986-431b-49339ac57427/volume/aggregate/chardet-feedstock/recipe, last modified Wed Nov  6 03:49:11 2019
# ------------------------------------------------

package:
    name: chardet
    version: 3.0.4
source:
    sha256: 84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae
    url: https://pypi.io/packages/source/c/chardet/chardet-3.0.4.tar.gz
build:
    entry_points:
        - chardetect = chardet.cli.chardetect:main
    number: '1003'
    script: /opt/concourse/worker/volumes/live/2705da7e-52de-4986-431b-49339ac57427/volume/chardet_1573033780488/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_1003
requirements:
    host:
        - atomicwrites 1.3.0 py_0
        - attrs 19.3.0 py_0
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - more-itertools 7.2.0 py38_0
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - packaging 19.2 py_0
        - pip 19.3.1 py38_0
        - pluggy 0.13.0 py38_0
        - py 1.8.0 py_0
        - pyparsing 2.4.2 py_0
        - pytest 5.2.1 py38_0
        - pytest-runner 5.1 py_0
        - python 3.8.0 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - six 1.12.0 py38_1000
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wcwidth 0.1.7 py38_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    commands:
        - chardetect --help
    imports:
        - chardet
about:
    description: 'chardet is a character encoding auto-detector in Python.

        '
    dev_url: https://github.com/chardet/chardet
    doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
    doc_url: http://chardet.readthedocs.org/
    home: https://github.com/chardet/chardet
    license: LGPL2
    license_family: GPL
    license_file: LICENSE
    summary: Universal character encoding detector
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dan-blanchard
        - jschueller
        - nehaljwani
        - sigmavirus24
