# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/fe9f335a-417e-4043-7c74-79722fd553d5/volume/rsync-recipes/mkl_fft-1.1.0-python_3.8-on-osx, last modified Wed Jun 17 10:10:18 2020
# ------------------------------------------------

package:
    name: mkl_fft
    version: 1.1.0
source:
    sha256: bad1b957e457e9dc596b54047c741df5b6e78f677e2c8a67b62d8cbf2ce9ae83
    url: https://github.com/IntelPython/mkl_fft/archive/v1.1.0.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/fe9f335a-417e-4043-7c74-79722fd553d5/volume/mkl_fft_1592406945266/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        setup.py build install --single-version-externally-managed --record=record.txt
    string: py38hc64f4ea_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py38_0
        - cython 0.29.20 py38hb1e8313_0
        - intel-openmp 2019.4 233
        - libcxx 10.0.0 1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.4 233
        - mkl-devel 2019.4 233
        - mkl-include 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - ncurses 6.2 h0a44026_1
        - numpy-base 1.14.6 py38h6575580_4
        - numpy-devel 1.14.6 py38h4ba5984_4
        - openssl 1.1.1g h1de35cc_0
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.0 py38_0
        - six 1.15.0 py_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - blas 1.0 mkl
        - libcxx >=10.0.0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - nosetests -v mkl_fft
    imports:
        - mkl_fft
        - mkl_fft._numpy_fft
        - mkl_fft._scipy_fft
    requires:
        - nose
about:
    description: NumPy-based implementation of Fast Fourier Transform using Intel
        (R) Math Kernel Library. Supports in-place and out-of-place, 1D and ND complex
        FFT on arrays of single and double precision with arbitrary memory layout,
        so long as array strides are multiples of its itemsize.
    home: http://github.com/IntelPython/mkl_fft
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: NumPy-based implementation of Fast Fourier Transform using Intel (R)
        Math Kernel Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - oleksandr-pavlyk
