# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: llvm-openmp
    version: 10.0.0
source:
    sha256: 3b9ff29a45d0509a1e9667a0feb43538ef402ea8cfc7df3758a01f20df08adfa
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/openmp-10.0.0.src.tar.xz
build:
    ignore_run_exports:
        - _openmp_mutex
        - libgcc-ng
        - libstdcxx-ng
    number: 0
    run_exports:
        strong:
            - llvm-openmp >=10.0.0
    string: h28b9765_0
requirements:
    build:
        - bzip2 1.0.8 h1de35cc_0
        - ca-certificates 2020.1.1 0
        - clang_bootstrap_osx-64 10.0.0 h05bbb7f_0
        - cmake 3.14.0 haff7e42_0
        - expat 2.2.6 h0a44026_0
        - krb5 1.17.1 hddcf347_0
        - libcurl 7.69.1 h051b688_0
        - libcxx 10.0.0 1
        - libedit 3.1.20181209 hb402a30_0
        - libssh2 1.9.0 ha12b0ac_1
        - make 4.2.1 h3efe00b_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - perl 5.26.2 h4e221da_0
        - rhash 1.3.8 ha12b0ac_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    host:
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-tools 10.0.0 h21ff451_0
        - llvmdev 10.0.0 h21ff451_0
    run_constrained:
        - clangdev 10.0.0|10.0.0.*
        - llvmdev 10.0.0|10.0.0.*
        - openmp 10.0.0|10.0.0.*
test:
    commands:
        - test -f $PREFIX/lib/libomp.dylib
        - test -f $PREFIX/include/omp.h
        - $PREFIX/bin/clang -v -fopenmp -I$PREFIX/include -L$PREFIX/lib -Wl,-rpath,$PREFIX/lib
            omp_hello.c -o omp_hello
        - ./omp_hello
    files:
        - omp_hello.c
    requires:
        - clang_bootstrap_osx-64 *
        - clangxx
about:
    home: http://openmp.llvm.org/
    license: NCSA
    license_file: LICENSE.txt
    summary: The OpenMP API supports multi-platform shared-memory parallel programming
        in C/C++ and Fortran.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - beckermr
        - inducer
        - isuruf
        - jakirkham
        - yesimon
