# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/dda3145d-3412-4412-6b2e-4baf7b4f423c/volume/aggregate/traitlets-feedstock/recipe, last modified Tue Nov 12 04:29:21 2019
# ------------------------------------------------

package:
    name: traitlets
    version: 4.3.3
source:
    sha256: d023ee369ddd2763310e4c3eae1ff649689440d4ae59d7485eb4cfbbe3e359f7
    url: https://pypi.io/packages/source/t/traitlets/traitlets-4.3.3.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/dda3145d-3412-4412-6b2e-4baf7b4f423c/volume/traitlets_1573555008720/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - decorator
        - ipython_genutils
        - python >=3.8,<3.9.0a0
        - six
test:
    imports:
        - traitlets
        - traitlets.config
about:
    description: 'Traitlets is a framework that lets Python classes have attributes
        with

        type checking, dynamically calculated default values, and "on change"

        callbacks.

        '
    dev_url: https://github.com/ipython/traitlets
    doc_source_url: https://github.com/ipython/traitlets/blob/master/docs/source/index.rst
    doc_url: http://traitlets.readthedocs.org/en/stable/
    home: http://ipython.org/
    license: BSD-3-Clause
    license_file: COPYING.md
    summary: Configuration system for Python applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
