# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/e256b37b-5ddb-497b-70d2-b2b61f847d6b/volume/aggregate/boto-feedstock/recipe, last modified Tue Oct 29 08:59:53 2019
# ------------------------------------------------

package:
    name: boto
    version: 2.49.0
source:
    fn: boto-2.49.0.tar.gz
    sha256: ea0d3b40a2d852767be77ca343b58a9e3a4b00d9db440efb8da74b4e58025e5a
    url: https://pypi.org/packages/source/b/boto/boto-2.49.0.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_0
        - readline 7.0 h1de35cc_5
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    commands:
        - s3put -h
    imports:
        - boto
about:
    description: 'Boto aims to support the full breadth and depth of Amazon Web Services.

        NOTE: Boto3, the next version of Boto, is stable and recommended for

        general use.

        '
    dev_url: https://github.com/boto/boto/
    doc_source_url: https://github.com/boto/boto/blob/develop/docs/source/index.rst
    doc_url: http://docs.pythonboto.org/en/latest/
    home: https://github.com/boto/boto/
    license: MIT
    summary: Amazon Web Services Library
extra:
    copy_test_source_files: true
    final: true
