# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/e1c2d77a-2feb-4538-7458-3a1d0c55819b/volume/rsync-recipes/pyodbc-4.0.30-python_3.8-on-osx, last modified Mon Feb 10 10:47:12 2020
# ------------------------------------------------

package:
    name: pyodbc
    version: 4.0.30
source:
    fn: pyodbc-4.0.30.tar.gz
    patches:
        - setup.patch
    sha256: 1be68880d64deffa6a57dca776be83d8367d81357642d24c8b2a3151921b7cd5
    url: https://github.com/mkleehammer/pyodbc/archive/4.0.30.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/e1c2d77a-2feb-4538-7458-3a1d0c55819b/volume/pyodbc_1581353954675/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps -vv
    string: py38h0a44026_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - libiconv 1.15 hdd342a3_7
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 20.0.2 py38_1
        - python 3.8.1 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 45.1.0 py38_0
        - sqlite 3.31.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - unixodbc 2.3.7 h1de35cc_0
        - wheel 0.34.2 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcxx >=4.0.1
        - python >=3.8,<3.9.0a0
        - unixodbc >=2.3.7,<2.4.0a0
test:
    imports:
        - pyodbc
about:
    description: 'pyodbc is a Python DB API 2 module for ODBC. This project provides
        an

        up-to-date, convenient interface to ODBC using native data types like

        datetime and decimal.

        '
    dev_url: https://github.com/mkleehammer/pyodbc
    doc_source_url: https://github.com/mkleehammer/pyodbc/blob/master/docs/index.md
    doc_url: http://mkleehammer.github.io/pyodbc/
    home: https://github.com/mkleehammer/pyodbc
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: DB API Module for ODBC
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
