# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/850161f9-7439-45f9-512e-2440fefbbbcc/volume/rsync-recipes/expat-2.2.9-on-osx, last modified Thu Jun 25 14:23:56 2020
# ------------------------------------------------

package:
    name: expat
    version: 2.2.9
source:
    sha256: f1063084dc4302a427dabcca499c8312b3a32a29b7d2506653ecc8f950a9a237
    url: https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.bz2
build:
    number: '2'
    run_exports:
        - expat >=2.2.9,<3.0a0
    string: hb1e8313_2
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - make 4.2.1 h3efe00b_1
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - libcxx 10.0.0 1
    run:
        - libcxx >=10.0.0
test:
    commands:
        - xmlwf -h
about:
    home: http://expat.sourceforge.net/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: Expat XML parser library in C
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kwilcox
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
