# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/47090e1c-dc82-4ab8-7ab0-318c9b6b0520/volume/rsync-recipes/python-3.8.3-on-osx, last modified Thu Jul  2 11:01:08 2020
# ------------------------------------------------

package:
    name: python
    version: 3.8.3
source:
    -   md5: 3000cf50aaa413052aef82fd2122ca78
        patches:
            - patches/0000-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
            - patches/0001-Add-Anaconda-Distribution-version-logic.patch
            - patches/0002-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - patches/0003-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - patches/0004-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - patches/0005-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - patches/0006-Support-cross-compiling-byte-code.patch
            - patches/0007-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - patches/0008-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - patches/0010-Win32-Do-not-download-externals.patch
            - patches/0011-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
            - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
            - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
            - patches/0014-Fix-cross-compilation-on-Debian-based-distros.patch
            - patches/0015-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
            - patches/0016-Unvendor-openssl.patch
            - patches/0017-Unvendor-sqlite3.patch
            - patches/0018-venv-Revert-a-change-from-https-github.com-python-cp.patch
            - patches/0019-Win-Add-back-the-DLLSuffix-used-to-find-the-openssl-.patch
            - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
            - patches/0021-roll-back-2e33ecd-for-py_compile.main.patch
            - patches/0022-Add-CondaEcosystemModifyDllSearchPath.patch
            - patches/0025-egg-debugging-with-Windows-debug-builds.patch
            - patches/0026-Revert-part-of-https-bugs.python.org-issue33895-http.patch
        url: https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tar.xz
build:
    binary_has_prefix_files:
        - lib/libpython3.dylib
    detect_binary_files_with_prefix: false
    ignore_run_exports:
        - bzip2
        - libcxx
        - libcxxabi
    number: '2'
    script_env:
        - PY_INTERP_DEBUG
        - PY_INTERP_LINKAGE_NATURE
    string: h26836e1_2
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libiconv 1.16 h1de35cc_0
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - make 4.2.1 h3efe00b_1
        - patch 2.7.6 h1de35cc_1001
        - pkg-config 0.29.2 h3efe00b_8
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - bzip2 1.0.8 h1de35cc_0
        - ca-certificates 2020.6.24 0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 h0a44026_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - readline 8.0 h1de35cc_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libffi >=3.3,<3.4.0a0
        - ncurses >=6.2,<7.0a0
        - openssl >=1.1.1g,<1.1.2a
        - readline >=8.0,<9.0a0
        - sqlite >=3.32.3,<4.0a0
        - tk >=8.6.10,<8.7.0a0
        - xz >=5.2.5,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - python -V
        - python3 -V
        - 2to3 -h
        - pydoc -h
        - python3-config --help
        - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
            if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
        - pushd tests
        - pushd distutils
        - python setup.py install -v -v
        - python -c "import foobar"
        - popd
        - pushd distutils.cext
        - python setup.py install -v -v
        - python -v -v -v -c "import greet"
        - python -v -v -v -c "import greet; greet.greet('Python user')" | rg "Hello
            Python"
        - popd
        - pushd prefix-replacement
        - bash build-and-test.sh
        - popd
        - pushd processpoolexecutor-max_workers-61
        - python ppe.py
        - popd
        - pushd cmake
        - export CMAKE_DBG=
        - cmake -GNinja -DPY_VER=3.8.3 -DPython_ROOT_DIR=${PREFIX} ${CMAKE_DBG} .
        - popd
        - popd
    files:
        - tests/cmake/*
        - tests/cython/*
        - tests/distutils.cext/*
        - tests/distutils/*
        - tests/prefix-replacement/*
        - tests/processpoolexecutor-max_workers-61/*
    requires:
        - clang_osx-64 10.*
        - clangxx_osx-64 10.*
        - cmake
        - cython
        - ninja
        - ripgrep
        - setuptools
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
