# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/ec098701-cad7-4317-4576-0365c5f66992/volume/pull-recipes-distributed/recipe, last modified Thu Jul  9 22:00:33 2020
# ------------------------------------------------

package:
    name: distributed
    version: 2.20.0
source:
    sha256: 76cb6c32597a8bf42f070033ff587603954285310b1b60d99b2fcd77bddfc23a
    url: https://pypi.io/packages/source/d/distributed/distributed-2.20.0.tar.gz
build:
    entry_points:
        - dask-scheduler=distributed.cli.dask_scheduler:go
        - dask-ssh=distributed.cli.dask_ssh:go
        - dask-worker=distributed.cli.dask_worker:go
    number: '0'
    script: /opt/concourse/worker/volumes/live/ec098701-cad7-4317-4576-0365c5f66992/volume/distributed_1594350140096/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_0
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - click >=6.6
        - cloudpickle >=1.3.0
        - cytoolz >=0.8.2
        - dask-core >=2.9.0
        - msgpack-python >=0.6.0
        - psutil >=5.0
        - python >=3.8,<3.9.0a0
        - pyyaml
        - setuptools
        - sortedcontainers !=2.0.0,!=2.0.1
        - tblib >=1.6.0
        - toolz >=0.8.2
        - tornado >=6.0.3
        - zict >=0.1.3
    run_constrained:
        - openssl !=1.1.1e
test:
    commands:
        - dask-scheduler --help
        - dask-ssh --help
        - dask-worker --help
    imports:
        - distributed
        - distributed.cli
        - distributed.comm
        - distributed.deploy
        - distributed.diagnostics
        - distributed.protocol
about:
    description: 'Distributed is a lightweight library for distributed computing in
        Python.

        It extends both the concurrent.futures and dask APIs to moderate sized

        clusters.

        '
    dev_url: https://github.com/dask/distributed
    doc_source_url: https://github.com/dask/distributed/blob/master/docs/source/index.rst
    doc_url: https://distributed.dask.org
    home: http://distributed.readthedocs.io/en/latest/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Distributed computing with Dask
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jcrist
        - jrbourbeau
        - marcelotrevisani
        - martindurant
        - mrocklin
        - ogrisel
        - tomaugspurger
