# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/xlsxwriter-1.2.9-on-linux_64, last modified Tue Jun  9 18:13:46 2020
# ------------------------------------------------

package:
    name: xlsxwriter
    version: 1.2.9
source:
    fn: XlsxWriter-1.2.9.tar.gz
    sha256: 828b3285fc95105f5b1946a6a015b31cf388bd5378fdc6604e4d1b7839df2e77
    url: https://pypi.io/packages/source/X/XlsxWriter/XlsxWriter-1.2.9.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/xlsxwriter_1591726538743/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_3
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.1.1 py36_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - xlsxwriter
about:
    description: 'XlsxWriter is a Python module that can be used to write text, numbers,
        formulas

        and hyperlinks to multiple worksheets in an Excel 2007+ XLSX file.

        '
    dev_url: https://github.com/jmcnamara/XlsxWriter
    doc_source_url: https://github.com/jmcnamara/XlsxWriter/blob/master/docs/XlsxWriter.pdf
    doc_url: https://xlsxwriter.readthedocs.org/
    home: https://xlsxwriter.readthedocs.io/
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: A Python module for creating Excel XLSX files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mcs07
        - nehaljwani
