# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/32abbe38-f42e-4419-5cb0-51ef727e26b6/volume/rsync-recipes/bottleneck-1.3.2-python_3.8-on-osx, last modified Wed Jun 10 04:01:46 2020
# ------------------------------------------------

package:
    name: bottleneck
    version: 1.3.2
source:
    sha256: 20179f0b66359792ea283b69aa16366419132f3b6cf3adadc0c48e2e8118e573
    url: https://pypi.io/packages/source/B/Bottleneck/Bottleneck-1.3.2.tar.gz
build:
    number: '1'
    script: /opt/concourse/worker/volumes/live/32abbe38-f42e-4419-5cb0-51ef727e26b6/volume/bottleneck_1591779926539/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . -vv
    string: py38hf1fa96c_1
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - intel-openmp 2019.4 233
        - libcxx 10.0.0 1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - mkl_fft 1.0.15 py38h5e564d8_0
        - mkl_random 1.1.1 py38h959d312_0
        - ncurses 6.2 h0a44026_1
        - numpy 1.14.6 py38h5fd8802_4
        - numpy-base 1.14.6 py38h6575580_4
        - openssl 1.1.1g h1de35cc_0
        - pip 20.0.2 py38_3
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 47.1.1 py38_0
        - six 1.15.0 py_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - python -c "import bottleneck; bottleneck.test()"
    imports:
        - bottleneck
        - bottleneck.move
        - bottleneck.nonreduce
        - bottleneck.nonreduce_axis
        - bottleneck.reduce
        - bottleneck.slow
        - bottleneck.tests
    requires:
        - pytest
about:
    description: 'Bottleneck is a collection of fast NumPy array functions written
        in

        Cython.

        '
    dev_url: https://github.com/pydata/bottleneck
    doc_url: https://bottleneck.readthedocs.io
    home: https://github.com/pydata/bottleneck
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Fast NumPy array functions written in Cython.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - qwhelan
        - wesm
