# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/c326af56-7768-4b51-7338-ab2448f0b9b7/volume/rsync-recipes/kiwisolver-1.2.0-python_3.8-on-osx, last modified Sun May  3 17:34:43 2020
# ------------------------------------------------

package:
    name: kiwisolver
    version: 1.2.0
source:
    sha256: 247800260cd38160c362d211dcaf4ed0f7816afb5efe56544748b21d6ad6d17f
    url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-1.2.0.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/c326af56-7768-4b51-7338-ab2448f0b9b7/volume/kiwisolver_1588546349638/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38h04f5b5a_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - cppy 1.1.0 py_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h0a44026_6
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.0.2 py38_1
        - python 3.8.2 hc70fcce_0
        - readline 8.0 h1de35cc_0
        - setuptools 46.1.3 py38_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcxx >=4.0.1
        - python >=3.8,<3.9.0a0
test:
    imports:
        - kiwisolver
about:
    description: 'Kiwi is an implementation of the algorithm based on the seminal

        Cassowary paper.It is not a refactoring of the original C++ solver.

        Kiwi has been designed from the ground up to be lightweight and fast.

        '
    dev_url: https://github.com/nucleic/kiwi
    doc_source_url: https://github.com/nucleic/kiwi/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/kiwisolver
    home: https://github.com/nucleic/kiwi
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: An efficient C++ implementation of the Cassowary constraint solver
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MatthieuDartiailh
        - blink1073
        - ericdill
        - licode
        - ocefpaf
        - sccolbert
        - tacaswell
