# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/cefb2791-3622-408a-6b93-9b5ae536805d/volume/rsync-recipes/lazy-object-proxy-1.4.3-python_3.8-on-osx, last modified Wed Nov  6 16:33:22 2019
# ------------------------------------------------

package:
    name: lazy-object-proxy
    version: 1.4.3
source:
    sha256: f3900e8a5de27447acbf900b4750b0ddfd7ec1ea7fbaf11dfa911141bc522af0
    url: https://pypi.io/packages/source/l/lazy-object-proxy/lazy-object-proxy-1.4.3.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/cefb2791-3622-408a-6b93-9b5ae536805d/volume/lazy-object-proxy_1573080599877/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps -vv
    string: py38h1de35cc_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - setuptools_scm 3.3.3 py_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - lazy_object_proxy
        - lazy_object_proxy.cext
about:
    dev_url: https://github.com/ionelmc/python-lazy-object-proxy
    doc_source_url: https://github.com/ionelmc/python-lazy-object-proxy/blob/master/docs/index.rst
    doc_url: https://python-lazy-object-proxy.readthedocs.org
    home: https://github.com/ionelmc/python-lazy-object-proxy
    license: BSD-2-Clause
    license_file: LICENSE
    summary: A fast and thorough lazy object proxy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
        - ocefpaf
