# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/17f29d61-5ea3-4c89-5652-e89dade6f19c/volume/rsync-recipes/snappy-1.1.8-on-osx, last modified Mon Jun 22 17:49:48 2020
# ------------------------------------------------

package:
    name: snappy
    version: 1.1.8
source:
    fn: snappy-1.1.8.tar.gz
    patches:
        - skip-microbenchmarks.patch
        - windows-static-lib-name.patch
    sha256: 16b677f07832a612b0836178db7f374e414f94657c138e6993cbfc5dcc58651f
    url: https://github.com/google/snappy/archive/1.1.8.tar.gz
build:
    number: '0'
    run_exports:
        - snappy >=1.1.8,<2.0a0
    string: hb1e8313_0
requirements:
    build:
        - bzip2 1.0.8 h1de35cc_0
        - ca-certificates 2020.1.1 0
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - cmake 3.14.0 haff7e42_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - expat 2.2.6 h0a44026_0
        - krb5 1.17.1 hddcf347_0
        - ld64 450.3 h3c32e8a_4
        - libcurl 7.69.1 h051b688_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libllvm10 10.0.0 h21ff451_0
        - libssh2 1.9.0 ha12b0ac_1
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - make 4.2.1 h3efe00b_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - rhash 1.3.8 ha12b0ac_0
        - tapi 1000.10.8 ha1b3eb9_0
        - tk 8.6.10 hb0a8c7a_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    host:
        - libcxx 10.0.0 1
    run:
        - libcxx >=10.0.0
test:
    commands:
        - test -e $PREFIX/include/snappy.h
        - test -e $PREFIX/include/snappy-stubs-public.h
        - test -e $PREFIX/lib/libsnappy$SHLIB_EXT
        - test -e $PREFIX/lib/libsnappy.a
about:
    description: 'Snappy is a compression/decompression library. It does not aim for
        maximum

        compression, or compatibility with any other compression library; instead,
        it

        aims for very high speeds and reasonable compression. For instance, compared
        to

        the fastest mode of zlib, Snappy is an order of magnitude faster for most

        inputs, but the resulting compressed files are anywhere from 20% to 100%

        bigger.

        '
    dev_url: https://github.com/google/snappy
    home: https://github.com/google/snappy
    license: BSD 3-clause
    license_family: BSD
    license_file: COPYING
    summary: A fast compressor/decompressor
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MaxRis
        - dougalsutherland
        - groutr
        - jakirkham
        - wesm
        - xhochy
