# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/0291c9e1-4b15-459f-623e-2770f55be269/volume/pull-recipes-appnope/recipe, last modified Thu Jul  9 18:45:08 2020
# ------------------------------------------------

package:
    name: appnope
    version: 0.1.0
source:
    sha256: 8b995ffe925347a2138d7ac0fe77155e4311a0ea6d6da4f5128fe4b3cbe5ed71
    url: https://pypi.io/packages/source/a/appnope/appnope-0.1.0.tar.gz
build:
    number: '1001'
    script: /opt/concourse/worker/volumes/live/0291c9e1-4b15-459f-623e-2770f55be269/volume/appnope_1594338395037/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_1001
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - appnope
about:
    description: 'appnope is a simple package for disabling App Nap on OS X 10.9,
        which can be problematic.

        '
    dev_url: https://github.com/minrk/appnope
    doc_source_url: https://github.com/minrk/appnope/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/appnope/0.1.0
    home: http://github.com/minrk/appnope
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Disable App Nap on OS X 10.9
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
        - ocefpaf
