# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/bleach-3.1.5-on-linux_64, last modified Tue Jun 16 17:55:23 2020
# ------------------------------------------------

package:
    name: bleach
    version: 3.1.5
source:
    sha256: 3c4c520fdb9db59ef139915a5db79f8b51bc2a7257ea0389f30c846883430a4b
    url: https://pypi.io/packages/source/b/bleach/bleach-3.1.5.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/bleach_1592330183391/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_3
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.1.1 py36_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - packaging
        - python
        - setuptools
        - six
        - webencodings
test:
    commands:
        - pip check
    imports:
        - bleach
    requires:
        - pip
about:
    description: 'Bleach is an allowed-list-based HTML sanitizing library that escapes
        or

        strips markup and attributes.

        '
    dev_url: https://github.com/mozilla/bleach
    doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst
    doc_url: https://bleach.readthedocs.io/
    home: https://github.com/mozilla/bleach
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: Easy, whitelist-based HTML-sanitizing tool
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
