# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/2708b935-9f8c-48e1-57fb-c82f246ebd2d/volume/rsync-recipes/ripgrep-11.0.2-on-osx, last modified Mon Oct 21 10:55:48 2019
# ------------------------------------------------

package:
    name: ripgrep
    version: 11.0.2
source:
    url: https://github.com/BurntSushi/ripgrep/archive/11.0.2.tar.gz
build:
    missing_dso_whitelist:
        - /usr/lib/libresolv.9.dylib
    script:
        - cargo build --release -v
        - $STRIP target/release/rg
        - mkdir $PREFIX/bin
        - cp target/release/rg $PREFIX/bin/rg
    string: he32d670_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - rust 1.40.0 h1de35cc_1
        - rust_osx-64 1.40.0 h0a44026_1
extra:
    copy_test_source_files: true
    final: true
