# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/d7cddb25-942b-45a8-6f21-ac3958c592c2/volume/rsync-recipes/scikit-image-0.16.2-python_3.8-on-osx, last modified Wed Jan 29 17:47:30 2020
# ------------------------------------------------

package:
    name: scikit-image
    version: 0.16.2
source:
    sha256: dd7fbd32da74d4e9967dc15845f731f16e7966cee61f5dc0e12e2abb1305068c
    url: https://pypi.io/packages/source/s/scikit-image/scikit-image-0.16.2.tar.gz
build:
    entry_points:
        - skivi = skimage.scripts.skivi:main
    number: '0'
    script:
        - rm -rf skimage/viewer/tests
        - /opt/concourse/worker/volumes/live/d7cddb25-942b-45a8-6f21-ac3958c592c2/volume/scikit-image_1580489918791/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
            -m pip install . --no-deps -vv
    string: py38h6c726b0_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_0
        - cython 0.29.14 py38h0a44026_0
        - intel-openmp 2019.4 233
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - mkl_fft 1.0.15 py38h5e564d8_0
        - mkl_random 1.1.0 py38h6440ff4_0
        - ncurses 6.1 h0a44026_1
        - numpy 1.14.6 py38h5fd8802_4
        - numpy-base 1.14.6 py38h6575580_4
        - openssl 1.1.1d h1de35cc_3
        - pip 20.0.2 py38_1
        - python 3.8.1 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 45.1.0 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.1 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - cloudpickle >=0.2.1
        - cytoolz >=0.7.3
        - dask-core >=0.15.0
        - imageio >=2.3.0
        - libcxx >=4.0.1
        - matplotlib >=2.0.0
        - networkx >=2.0
        - numpy >=1.14.6,<2.0a0
        - pillow >=4.3.0
        - python >=3.8,<3.9.0a0
        - pywavelets >=0.4.0
        - scipy >=0.19
        - toolz >=0.7.3
test:
    commands:
        - export MPLBACKEND=Agg
        - pytest --pyargs skimage
    imports:
        - skimage
    requires:
        - pytest
        - pytest-localserver
about:
    home: http://scikit-image.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Image processing routines for SciPy.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hmaarrfk
        - ivoflipse
        - jakirkham
        - jni
        - msarahan
        - ocefpaf
        - soupault
