# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/d419014f-853b-4153-64e3-446f011b603d/volume/aggregate/pandocfilters-feedstock/recipe, last modified Mon Nov 11 10:37:06 2019
# ------------------------------------------------

package:
    name: pandocfilters
    version: 1.4.2
source:
    fn: pandocfilters-1.4.2.tar.gz
    sha256: b3dd70e169bb5449e6bc6ff96aea89c5eea8c5f6ab5e207fc2f521a2cf4a0da9
    url: https://pypi.io/packages/source/p/pandocfilters/pandocfilters-1.4.2.tar.gz
build:
    number: '1'
    script: pip install --no-deps .
    string: py38_1
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - pandocfilters
about:
    dev_url: https://github.com/jgm/pandocfilters
    home: https://github.com/jgm/pandocfilters
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A python module for writing pandoc filters
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
