# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/93a9c6ee-7d77-4975-4d26-29732dd5574b/volume/rsync-recipes/regex-2020.6.8-python_3.8-on-osx, last modified Sun Jun 28 12:28:02 2020
# ------------------------------------------------

package:
    name: regex
    version: 2020.6.8
source:
    sha256: e9b64e609d37438f7d6e68c2546d2cb8062f3adb27e6336bc129b51be20773ac
    url: https://pypi.io/packages/source/r/regex/regex-2020.6.8.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/93a9c6ee-7d77-4975-4d26-29732dd5574b/volume/regex_1593435592218/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py38haf1e3a3_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 h0a44026_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - regex
about:
    home: https://bitbucket.org/mrabarnett/mrab-regex
    license: Python-2.0
    license_family: PSF
    summary: Alternative regular expression module, to replace re
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kwilcox
        - ocefpaf
        - xhochy
