# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/7f5e51f8-abf3-4409-4c56-a4fb14cc9869/volume/rsync-recipes/scipy-1.5.0-python_3.8-blas_impl_mkl-on-osx, last modified Tue Jun 23 11:40:05 2020
# ------------------------------------------------

package:
    name: scipy
    version: 1.5.0
source:
    sha256: 28a1039b8616e4c4a5de32994f1d7a6c7281429158daa23920e9fecbbd0272e1
    url: https://github.com/scipy/scipy/archive/v1.5.0.tar.gz
build:
    number: '0'
    string: py38hbab996c_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - clangxx_osx-64 10.0.0 h05bbb7f_1
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - gfortran_osx-64 4.8.5 h22b1bf0_8
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libgfortran 3.0.1 h93005f0_2
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.20 py38hb1e8313_0
        - intel-openmp 2019.4 233
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 h0a44026_1
        - libgfortran 3.0.1 h93005f0_2
        - mkl 2019.4 233
        - mkl-devel 2019.4 233
        - mkl-include 2019.4 233
        - mkl-service 2.3.0 py38hfbe908c_0
        - ncurses 6.2 h0a44026_1
        - numpy-base 1.16.6 py38h6575580_0
        - numpy-devel 1.16.6 py38h4ba5984_0
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - pybind11 2.4.3 py38h04f5b5a_0
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - six 1.15.0 py_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - blas 1.0 mkl
        - libcxx >=10.0.0
        - libgfortran >=3.0.1,<4.0.0.a0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.16.6,<2.0a0
        - python >=3.8,<3.9.0a0
test:
    requires:
        - intel-openmp 2019.*
        - mpmath
        - pytest
        - pytest-xdist
about:
    description: 'SciPy is a Python-based ecosystem of open-source software for mathematics,

        science, and engineering.

        '
    dev_url: https://github.com/scipy/scipy
    doc_url: http://www.scipy.org/docs.html
    home: http://www.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Scientific Library for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - rgommers
