# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/9ab2d8c9-cf92-410b-7790-75d504571409/volume/rsync-recipes/lzo-2.10-on-osx, last modified Thu Apr 16 09:12:43 2020
# ------------------------------------------------

package:
    name: lzo
    version: '2.10'
source:
    sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
    url: http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
build:
    number: '2'
    run_exports:
        - lzo >=2.10,<3.0a0
    string: h1de35cc_2
requirements:
    build:
        - bzip2 1.0.8 h1de35cc_0
        - ca-certificates 2020.1.1 0
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - cmake 3.14.0 haff7e42_0
        - compiler-rt 4.0.1 hcfea43d_1
        - expat 2.2.6 h0a44026_0
        - krb5 1.17.1 hddcf347_0
        - ld64 274.2 1
        - libcurl 7.69.1 h051b688_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libssh2 1.9.0 ha12b0ac_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - make 4.2.1 h3efe00b_1
        - ncurses 6.2 h0a44026_0
        - openssl 1.1.1f h1de35cc_0
        - rhash 1.3.8 ha12b0ac_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    host:
        - ripgrep 11.0.2 he32d670_0
test:
    commands:
        - test -f ${PREFIX}/include/lzo/lzoconf.h
        - test -f ${PREFIX}/lib/liblzo2.a
        - test -f ${PREFIX}/lib/liblzo2${SHLIB_EXT}
about:
    description: 'LZO offers pretty fast compression and extremely fast decompression.

        MiniLZO is a very lightweight subset of the LZO library.

        '
    home: http://www.oberhumer.com/opensource/lzo/
    license: GPL v2+
    license_family: GPL2
    license_file: COPYING
    summary: LZO is a portable lossless data compression library written in ANSI C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - rmax
