# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a89ae5d9-4200-4f08-7083-6de90fdc229d/volume/aggregate/simplegeneric-feedstock/recipe, last modified Fri Nov  8 02:13:09 2019
# ------------------------------------------------

package:
    name: simplegeneric
    version: 0.8.1
source:
    fn: simplegeneric-0.8.1.zip
    md5: f9c1fab00fd981be588fc32759f474e3
    url: https://pypi.python.org/packages/source/s/simplegeneric/simplegeneric-0.8.1.zip
build:
    number: '2'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py38_2
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - simplegeneric
about:
    description: 'The simplegeneric module lets you define simple single-dispatch
        generic

        functions, akin to Python''s built-in generic functions like len(), iter()

        and so on. However, instead of using specially-named methods, these

        generic functions use simple lookup tables, akin to those used by e.g.

        pickle.dump() and other generic functions found in the Python standard

        library.

        '
    doc_url: https://pypi.python.org/pypi/simplegeneric
    home: http://cheeseshop.python.org/pypi/simplegeneric
    license: Zope Public
    summary: Simple generic functions (similar to Python's own len(), pickle.dump(),
        etc.)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - msarahan
        - pelson
