# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a029938e-1732-4cd8-5b98-0542283d158b/volume/pull-recipes-nose/recipe, last modified Fri Jul 10 05:44:17 2020
# ------------------------------------------------

package:
    name: nose
    version: 1.3.7
source:
    md5: 4d3ad0ff07b61373d2cefc89c5d0b20b
    url: https://pypi.io/packages/source/n/nose/nose-1.3.7.tar.gz
build:
    entry_points:
        - nosetests = nose:run_exit
    number: '1004'
    string: py38_1004
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
        - setuptools
test:
    commands:
        - nosetests -h
    imports:
        - nose
        - pkg_resources
about:
    description: 'NOTE: Nose has been in maintenance mode for the past several years
        and will

        likely cease without a new person/team to take over maintainership. New

        projects should consider using Nose2, py.test, or just plain

        unittest/unittest2.

        '
    dev_url: https://github.com/nose-devs/nose/
    doc_source_url: https://github.com/nose-devs/nose/blob/master/doc/index.rst
    doc_url: https://nose.readthedocs.org
    home: http://readthedocs.org/docs/nose/
    license: LGPL-2.1
    license_file: lgpl.txt
    summary: Nose extends unittest to make testing easier
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - scopatz
