# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/571bc08e-053e-4231-7266-50e35ded8305/volume/rsync-recipes/greenlet-0.4.16-python_3.8-on-osx, last modified Tue Jun 16 13:07:10 2020
# ------------------------------------------------

package:
    name: greenlet
    version: 0.4.16
source:
    fn: greenlet-0.4.16.tar.gz
    sha256: 6e06eac722676797e8fce4adb8ad3dc57a1bb3adfb0dd3fdf8306c055a38456c
    url: https://pypi.io/packages/source/g/greenlet/greenlet-0.4.16.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/571bc08e-053e-4231-7266-50e35ded8305/volume/greenlet_1592330944319/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install --no-deps --ignore-installed .
    string: py38haf1e3a3_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.0.2 py38_3
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 47.1.1 py38_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - greenlet
about:
    description: 'The greenlet package is a spin-off of Stackless, a version of CPython
        that

        supports micro-threads called "tasklets". Tasklets run pseudo-concurrently

        (typically in a single or a few OS-level threads) and are synchronized with

        data exchanges on "channels".


        A "greenlet", on the other hand, is a still more primitive notion of

        micro-thread with no implicit scheduling; coroutines, in other words. This

        is useful when you want to control exactly when your code runs. You can

        build custom scheduled micro-threads on top of greenlet; however, it seems

        that greenlets are useful on their own as a way to make advanced control

        flow structures. For example, we can recreate generators; the difference

        with Python''s own generators is that our generators can call nested

        functions and the nested functions can yield values too. Additionally,

        you don''t need a "yield" keyword. See the example in

        tests/test_generator.py.


        Greenlets are provided as a C extension module for the regular unmodified

        interpreter.


        Greenlets are lightweight coroutines for in-process concurrent programming.

        '
    dev_url: https://github.com/python-greenlet/greenlet
    doc_url: https://greenlet.readthedocs.io
    home: https://github.com/python-greenlet/greenlet
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Lightweight in-process concurrent programming
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - curtisalexander
        - nicoddemus
