# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/cb5649db-6f30-435c-6981-1014aa39f028/volume/rsync-recipes/ipykernel-5.3.2-python_3.8-on-osx, last modified Tue Jul 14 14:34:20 2020
# ------------------------------------------------

package:
    name: ipykernel
    version: 5.3.2
source:
    sha256: 89dc4bd19c7781f6d7eef0e666c59ce57beac56bb39b511544a71397b7b31cbb
    url: https://pypi.io/packages/source/i/ipykernel/ipykernel-5.3.2.tar.gz
build:
    number: '0'
    script:
        - /opt/concourse/worker/volumes/live/cb5649db-6f30-435c-6981-1014aa39f028/volume/ipykernel_1594755378873/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
            setup.py bdist_wheel
        - cd dist
        - /opt/concourse/worker/volumes/live/cb5649db-6f30-435c-6981-1014aa39f028/volume/ipykernel_1594755378873/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
            -m pip install ipykernel-5.3.2-py3-none-any.whl --no-deps -vv
        - /opt/concourse/worker/volumes/live/cb5649db-6f30-435c-6981-1014aa39f028/volume/ipykernel_1594755378873/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
            -m ipykernel install --sys-prefix
    string: py38h5ca1d4c_0
requirements:
    host:
        - appnope 0.1.0 py38_1001
        - backcall 0.2.0 py_0
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - decorator 4.4.2 py_0
        - entrypoints 0.3 py38_0
        - ipython 7.16.1 py38h5ca1d4c_0
        - ipython_genutils 0.2.0 py38_0
        - jedi 0.17.1 py38_0
        - jupyter_client 6.1.5 py_0
        - jupyter_core 4.6.3 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - libsodium 1.0.18 h1de35cc_0
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - parso 0.7.0 py_0
        - pexpect 4.8.0 py38_1
        - pickleshare 0.7.5 py38_1001
        - pip 20.1.1 py38_1
        - prompt-toolkit 3.0.5 py_0
        - ptyprocess 0.6.0 py38_0
        - pygments 2.6.1 py_0
        - python 3.8.3 h26836e1_2
        - python-dateutil 2.8.1 py_0
        - pyzmq 19.0.1 py38hb1e8313_1
        - readline 8.0 h1de35cc_0
        - setuptools 49.1.0 py38_0
        - six 1.15.0 py_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - tornado 6.0.4 py38h1de35cc_1
        - traitlets 4.3.3 py38_0
        - wcwidth 0.2.5 py_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zeromq 4.3.2 hb1e8313_2
        - zlib 1.2.11 h1de35cc_3
    run:
        - ipython >=5.0
        - jupyter_client
        - python >=3.8,<3.9.0a0
        - tornado >=4.2
        - traitlets >=4.1
test:
    commands:
        - jupyter kernelspec list
    imports:
        - ipykernel
    requires:
        - curio
        - flaky
        - ipython
        - nose
        - numpy
        - pytest !=5.3.4
about:
    description: 'A powerful interactive Python shell and a Jupyter kernel to work
        with

        Python code in Jupyter notebooks and other interactive frontends.

        '
    dev_url: https://github.com/ipython/ipykernel
    doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
    doc_url: https://ipython.readthedocs.io
    home: https://ipython.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: IPython Kernel for Jupyter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - blink1073
        - bollwyvl
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
