# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/qtawesome-0.7.2-on-linux_64, last modified Tue Jun 16 17:23:38 2020
# ------------------------------------------------

package:
    name: qtawesome
    version: 0.7.2
source:
    sha256: ca9719c82d41707f62c340811b23bcab95336e73edd88b7eab7fd951d2e27fab
    url: https://pypi.io/packages/source/q/qtawesome/QtAwesome-0.7.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/qtawesome_1592328329440/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    build:
        - libdrm-cos6-x86_64 2.4.65 hd39d64f_0
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - mesa-libgl-cos6-x86_64 11.0.7 h045e36e_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_3
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.1.1 py36_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
        - qtpy
        - six
test:
    imports:
        - qtawesome
    requires:
        - mesa-libgl-devel-cos6-x86_64
        - pyqt
about:
    home: https://github.com/spyder-ide/qtawesome
    license: MIT
    license_file: LICENSE.txt
    summary: Iconic fonts in PyQt and PySide applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - ccordoba12
        - dalthviz
        - goanpeca
