# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-intervaltree/recipe, last modified Fri Jul 10 06:14:01 2020
# ------------------------------------------------

package:
    name: intervaltree
    version: 3.0.2
source:
    fn: intervaltree-3.0.2.tar.gz
    sha256: cb4f61c81dcb4fea6c09903f3599015a83c9bdad1f0bbd232495e6681e19e273
    url: https://pypi.io/packages/source/i/intervaltree/intervaltree-3.0.2.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py37_1
        - python 3.7.7 hcff3b4d_5
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py37_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
        - sortedcontainers
test:
    imports:
        - intervaltree
about:
    home: https://github.com/chaimleib/intervaltree
    license: Apache-2.0
    license_family: APACHE
    license_file: LICENSE.txt
    summary: Editable interval tree data structure for Python 2 and 3
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bgruening
        - johanneskoester
