# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/c75931f5-f716-4583-44f8-f155376238bf/volume/rsync-recipes/dbus-1.13.16-on-osx, last modified Thu Jun 25 13:34:25 2020
# ------------------------------------------------

package:
    name: dbus
    version: 1.13.16
source:
    sha256: f56b0aa015d0cd13e235225484f411e3c587a0f852c12da03852a324dd1cafb3
    url: http://dbus.freedesktop.org/releases/dbus/dbus-1.13.16.tar.xz
build:
    number: '0'
    run_exports:
        - dbus >=1.13.16,<2.0a0
    string: h18a8e69_0
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libiconv 1.16 h1de35cc_0
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - make 4.2.1 h3efe00b_1
        - pkg-config 0.29.2 h3efe00b_8
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - expat 2.2.6 h0a44026_0
        - gettext 0.19.8.1 hb0f4f8b_2
        - glib 2.63.1 h70d4741_1
        - libcxx 10.0.0 1
        - libffi 3.3 h0a44026_1
        - libiconv 1.16 h1de35cc_0
        - pcre 8.44 hb1e8313_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - expat >=2.2.6,<3.0a0
        - glib >=2.63.1,<3.0a0
test:
    commands:
        - dbus-daemon --version
        - dbus-uuidgen
about:
    description: 'D-Bus is a message bus system, a simple way for applications

        to talk to one another. In addition to interprocess communication, D-Bus helps

        coordinate process lifecycle; it makes it simple and reliable to code a "single

        instance" application or daemon, and to launch applications and daemons on

        demand when their services are needed.

        '
    dev_url: git://anongit.freedesktop.org/dbus/dbus
    doc_source_url: https://cgit.freedesktop.org/dbus/dbus/tree/doc
    doc_url: https://www.freedesktop.org/wiki/IntroductionToDBus/
    home: http://www.freedesktop.org/wiki/Software/dbus/
    license: GPL2
    license_file: COPYING
    summary: Simple message bus system for applications to talk to one another
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - nehaljwani
        - ocefpaf
