# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/jupyter_console-6.1.0-on-linux_64, last modified Thu Jan 23 16:03:59 2020
# ------------------------------------------------

package:
    name: jupyter_console
    version: 6.1.0
source:
    sha256: 6f6ead433b0534909df789ea64f0a14cdf9b6b2360757756f08182be4b9e431b
    url: https://pypi.io/packages/source/j/jupyter_console/jupyter_console-6.1.0.tar.gz
build:
    entry_points:
        - jupyter-console = jupyter_console.app:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/jupyter_console_1579795566836/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py38_0
        - python 3.8.1 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 44.0.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - ipykernel
        - ipython
        - jupyter_client
        - prompt_toolkit >=2.0.0,<3.1.0,!=3.0.0,!=3.0.1
        - pygments
        - python >=3.5
test:
    commands:
        - jupyter-console -h
    imports:
        - jupyter_console
about:
    description: 'Jupyter console is a terminal frontend for kernels using the Jupyter
        protocol.

        '
    dev_url: https://github.com/jupyter/jupyter_console
    doc_source_url: https://github.com/jupyter/jupyter_console/blob/master/docs/index.rst
    doc_url: http://jupyter-console.readthedocs.org/
    home: http://jupyter.org
    license: BSD-3-Clause
    license_file: COPYING.md
    summary: Jupyter terminal console
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
        - takluyver
