# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/afa66bf4-57e8-49de-455b-18ffb1655f88/volume/pull-recipes-libedit/recipe, last modified Fri Jul 10 02:53:59 2020
# ------------------------------------------------

package:
    name: libedit
    version: 3.1.20191231
source:
    fn: libedit-20191231-3.1.tar.gz
    patches:
        - 0001-prefer-tinfo-over-curses-and-termcap.patch
    sha256: dbb82cb7e116a5f8025d35ef5b4f7d4a3cdd0a3909a146a39112095a2d229071
    url: https://github.com/AnacondaRecipes/libedit-feedstock/releases/download/source/libedit-20191231-3.1.tar.gz
build:
    number: '1'
    run_exports:
        - libedit >=3.1.20191231,<3.2.0a0
    string: h1de35cc_1
requirements:
    build:
        - autoconf 2.69 pl526he370928_5
        - automake 1.16.2 pl526_0
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - m4 1.4.18 h1de35cc_1
        - make 4.2.1 h3efe00b_1
        - perl 5.26.0 h5b8ca18_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - libcxx 10.0.0 1
        - ncurses 6.2 h0a44026_1
    run:
        - ncurses >=6.2,<7.0a0
test:
    commands:
        - test -f $PREFIX/lib/libedit.dylib
        - test ! -f $PREFIX/lib/libedit.a
about:
    description: 'This is an autotool- and libtoolized port of the NetBSD Editline
        library

        (libedit). This Berkeley-style licensed command line editor library provides

        generic line editing, history, and tokenization functions, similar to those

        found in GNU Readline

        '
    home: http://thrysoee.dk/editline/
    license: BSD-2-Clause
    license_family: BSD
    license_file: COPYING
    summary: Editline Library (libedit)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - djsutherland
        - mingwandroid
        - scopatz
