# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/tblib-1.6.0-on-linux_64, last modified Mon Dec 16 23:11:39 2019
# ------------------------------------------------

package:
    name: tblib
    version: 1.6.0
source:
    sha256: 229bee3754cb5d98b4837dd5c4405e80cfab57cb9f93220410ad367f8b352344
    url: https://pypi.org/packages/source/t/tblib/tblib-1.6.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py27_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py27_0
        - python 2.7.17 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 42.0.2 py27_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - tblib
about:
    description: 'tblib allows you to Pickle tracebacks and raise exceptions with
        pickled

        tracebacks in different processes.This allows better error handling when

        running code over multiple processes.

        '
    dev_url: https://github.com/ionelmc/python-tblib
    doc_source_url: https://github.com/ionelmc/python-tblib/blob/master/docs/index.rst
    doc_url: https://python-tblib.readthedocs.io/en/latest/
    home: https://github.com/ionelmc/python-tblib
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Traceback serialization library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
        - pmlandwehr
