# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f42dafd9-458f-4b82-585c-3d7b43d0a7e6/volume/rsync-recipes/jupyter_core-4.6.3-python_3.8-on-osx, last modified Tue Mar 31 03:55:26 2020
# ------------------------------------------------

package:
    name: jupyter_core
    version: 4.6.3
source:
    sha256: 394fd5dd787e7c8861741880bdf8a00ce39f95de5d18e579c74b882522219e7e
    url: https://pypi.io/packages/source/j/jupyter_core/jupyter_core-4.6.3.tar.gz
build:
    entry_points:
        - jupyter = jupyter_core.command:main
        - jupyter-migrate = jupyter_core.migrate:main
        - jupyter-troubleshoot = jupyter_core.troubleshoot:main
    number: '0'
    script: /opt/concourse/worker/volumes/live/f42dafd9-458f-4b82-585c-3d7b43d0a7e6/volume/jupyter_core_1585645817295/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps -vv
    string: py38_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.2 h0a44026_0
        - openssl 1.1.1e h1de35cc_0
        - pip 20.0.2 py38_1
        - python 3.8.2 hc70fcce_0
        - readline 8.0 h1de35cc_0
        - setuptools 46.1.3 py38_0
        - setuptools_scm 3.4.3 py_0
        - sqlite 3.31.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
        - traitlets
test:
    commands:
        - jupyter -h
        - jupyter-migrate -h
        - jupyter-troubleshoot --help
        - pip check
    imports:
        - jupyter_core
    requires:
        - nose
        - pip
        - pytest
about:
    dev_url: https://github.com/jupyter/jupyter_core
    doc_source_url: https://github.com/jupyter/jupyter_core/tree/master/docs
    doc_url: https://jupyter-core.readthedocs.io
    home: https://jupyter.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: Core common functionality of Jupyter projects.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - bollwyvl
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
