# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ipywidgets-7.5.1-on-linux_64, last modified Tue Aug  6 15:42:37 2019
# ------------------------------------------------

package:
    name: ipywidgets
    version: 7.5.1
source:
    sha256: e945f6e02854a74994c596d9db83444a1850c01648f1574adf144fbbabe05c97
    url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-7.5.1.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps .
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.5.15 0
        - certifi 2019.6.16 py27_1
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1c h7b6447c_1
        - pip 19.1.1 py27_0
        - python 2.7.16 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.0.1 py27_0
        - sqlite 3.29.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.4 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - ipykernel >=4.5.1
        - ipython >=4.0.0
        - nbformat >=4.2.0
        - python
        - traitlets >=4.3.1,<5.0.0
        - widgetsnbextension >=3.5.0,<3.6.0
test:
    imports:
        - ipywidgets
about:
    description: 'ipywidgets are interactive HTML widgets for Jupyter notebooks and
        the IPython kernel.

        '
    doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst
    doc_url: https://ipywidgets.readthedocs.io/en/latest/
    home: https://github.com/ipython/ipywidgets
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE
    summary: Jupyter Interactive Widgets
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - jakirkham
        - jasongrout
        - maartenbreddels
        - minrk
        - pbugnion
        - pelson
        - willingc
