# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/95802d64-d39c-491b-74ce-b9326880ca54/volume/pull-recipes-mistune/recipe, last modified Fri Jul 10 04:24:15 2020
# ------------------------------------------------

package:
    name: mistune
    version: 0.8.4
source:
    sha256: 59a3429db53c50b5c6bcc8a07f8848cb00d7dc8bdb431a4ab41920d201d4756e
    url: https://pypi.io/packages/source/m/mistune/mistune-0.8.4.tar.gz
build:
    number: '1001'
    script: /opt/concourse/worker/volumes/live/95802d64-d39c-491b-74ce-b9326880ca54/volume/mistune_1594373201816/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps -vv
    string: py38h1de35cc_1001
requirements:
    build:
        - cctools 927.0.2 h5ba7a2e_4
        - clang 10.0.0 default_hf57f61e_0
        - clang_osx-64 10.0.0 h05bbb7f_1
        - clangxx 10.0.0 default_hf57f61e_0
        - compiler-rt 10.0.0 h47ead80_0
        - compiler-rt_osx-64 10.0.0 hbcc88fd_0
        - ld64 450.3 h3c32e8a_4
        - libcxx 10.0.0 1
        - libllvm10 10.0.0 h21ff451_0
        - llvm-openmp 10.0.0 h28b9765_0
        - llvm-tools 10.0.0 h21ff451_0
        - tapi 1000.10.8 ha1b3eb9_0
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.20 py38hb1e8313_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 hb1e8313_2
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    commands:
        - nosetests
    imports:
        - mistune
    requires:
        - nose
        - python >=3.8,<3.9.0a0
    source_files:
        - tests
about:
    description: 'Inspired by https://github.com/chjj/marked, Mistune is the fastest
        markdown

        parser in pure Python with renderer features. More features include table,

        footnotes, autolink, fenced code etc.

        '
    dev_url: https://github.com/lepture/mistune
    doc_source_url: https://github.com/lepture/mistune/blob/master/README.rst
    doc_url: https://mistune.readthedocs.io/
    home: https://github.com/lepture/mistune
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: The fastest markdown parser in pure Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - ocefpaf
        - pelson
