# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/2a4d270d-717f-4844-4ef9-fd1fa4dc115a/volume/aggregate/unicodecsv-feedstock/recipe, last modified Fri Nov  8 02:05:33 2019
# ------------------------------------------------

package:
    name: unicodecsv
    version: 0.14.1
source:
    fn: unicodecsv-0.14.1.tar.gz
    sha256: 018c08037d48649a0412063ff4eda26eaa81eff1546dbffa51fa5293276ff7fc
    url: https://pypi.io/packages/source/u/unicodecsv/unicodecsv-0.14.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - unicodecsv
about:
    description: 'The unicodecsv is a drop-in replacement for Python 2.7''s csv module
        which

        supports unicode strings without a hassle. Supported versions are python

        2.6, 2.7, 3.3, 3.4, 3.5, and pypy 2.4.0.

        '
    dev_url: https://github.com/jdunck/python-unicodecsv
    home: https://github.com/jdunck/python-unicodecsv
    license: BSD
    license_family: BSD
    license_file: /opt/concourse/worker/volumes/live/2a4d270d-717f-4844-4ef9-fd1fa4dc115a/volume/aggregate/unicodecsv-feedstock/recipe/LICENSE
    summary: Drop-in replacement for csv module which supports unicode strings
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
