# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a5bb22d5-0f12-4611-6fd9-beeab08ca117/volume/rsync-recipes/psutil-5.7.0-python_3.8-on-osx, last modified Thu Mar 12 13:30:40 2020
# ------------------------------------------------

package:
    name: psutil
    version: 5.7.0
source:
    fn: psutil-5.7.0.tar.gz
    sha256: 685ec16ca14d079455892f25bd124df26ff9137664af445563c1bd36629b5e0e
    url: https://pypi.io/packages/source/p/psutil/psutil-5.7.0.tar.gz
build:
    number: '0'
    script: python -m pip install --ignore-installed --no-deps .
    string: py38h1de35cc_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.2 h0a44026_0
        - openssl 1.1.1d h1de35cc_4
        - pip 20.0.2 py38_1
        - python 3.8.1 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 46.0.0 py38_0
        - sqlite 3.31.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - psutil
        - psutil._psutil_osx
        - psutil._psutil_posix
        - psutil.tests
about:
    description: 'psutil (process and system utilities) is a cross-platform library
        for

        retrieving information on running processes and system utilization (CPU,

        memory, disks, network) in Python. It is useful mainly for system

        monitoring, profiling and limiting process resources and management of

        running processes.

        '
    dev_url: https://github.com/giampaolo/psutil
    doc_source_url: https://github.com/giampaolo/psutil/blob/master/docs/index.rst
    doc_url: http://pythonhosted.org/psutil/
    home: https://github.com/giampaolo/psutil
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A cross-platform process and system utilities module for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gqmelo
        - jakirkham
        - jjhelmus
        - nehaljwani
        - pelson
