# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/d40daf01-47dd-48dd-7afb-13c6f5630669/volume/rsync-recipes/anaconda-client-1.7.2-python_3.8-on-osx, last modified Tue Jan 28 15:15:18 2020
# ------------------------------------------------

package:
    name: anaconda-client
    version: 1.7.2
source:
    fn: anaconda-client-1.7.2.tar.gz
    sha256: 839bc07d5e3b9069180ad9c78bfb0b74ab7b4ccac9523a5b9d1d8aa0b154bab5
    url: https://github.com/Anaconda-Platform/anaconda-client/archive/1.7.2.tar.gz
build:
    entry_points:
        - anaconda = binstar_client.scripts.cli:main
        - binstar = binstar_client.scripts.cli:main
        - conda-server = binstar_client.scripts.cli:main
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 20.0.2 py38_0
        - python 3.8.1 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 45.1.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - clyent >=1.2.0
        - nbformat >=4.4.0
        - python >=3.8,<3.9.0a0
        - python-dateutil >=2.6.1
        - pytz
        - pyyaml >=3.12
        - requests >=2.9.1
        - setuptools
        - six
test:
    commands:
        - anaconda --help
        - binstar --help
        - conda-server --help
    imports:
        - binstar_client
        - binstar_client.commands
        - binstar_client.inspect_package
        - binstar_client.inspect_package.tests
        - binstar_client.mixins
        - binstar_client.scripts
        - binstar_client.tests
        - binstar_client.utils
        - binstar_client.utils.notebook
        - binstar_client.utils.notebook.tests
about:
    dev_url: https://github.com/Anaconda-Platform/anaconda-client
    doc_url: https://docs.anaconda.com/anaconda-cloud/user-guide/getting-started/
    home: https://github.com/Anaconda-Platform/anaconda-client
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.md
    summary: Anaconda Cloud command line client library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - jakirkham
