# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/4b1c2b3a-ad4b-4d97-75d9-cf0470289b17/volume/rsync-recipes/pandoc-2.10-on-osx, last modified Wed Jul 15 11:25:18 2020
# ------------------------------------------------

package:
    name: pandoc
    version: '2.10'
source:
    sha256: 5def6e20968952d08aa742e9bcfca7feda2f0d314695053647f76db3dc27d4a9
    url: https://github.com/jgm/pandoc/releases/download/2.10/pandoc-2.10-macOS.zip
build:
    binary_relocation: false
    missing_dso_whitelist:
        - /usr/lib/libcharset.1.dylib
        - /usr/lib/libiconv.2.dylib
        - /usr/lib/libz.1.dylib
    number: '0'
    string: '0'
test:
    commands:
        - type pandoc
        - pandoc --version
        - pandoc --help
about:
    description: 'Pandoc is a Haskell library for converting from one markup format
        to

        another, and a command-line tool that uses this library.

        '
    dev_url: https://github.com/jgm/pandoc
    doc_source_url: https://github.com/jgm/pandoc/tree/master/doc
    doc_url: http://pandoc.org/MANUAL.html
    home: http://pandoc.org/
    license: GPL-2.0
    license_family: GPL
    license_file: LICENSE
    summary: Universal markup converter (repackaged binaries)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dhimmel
        - jankatins
        - kiwi0fruit
        - ocefpaf
