# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a3871457-b264-4197-7e6e-ab5e82525663/volume/aggregate/mkl-service-feedstock/recipe, last modified Mon Nov 11 10:02:41 2019
# ------------------------------------------------

package:
    name: mkl-service
    version: 2.3.0
source:
    sha256: f0c61f44f29d1264a464c14791b042826f0f74da094c3355dcc295943c46fed5
    url: https://github.com/IntelPython/mkl-service/archive/v2.3.0.tar.gz
build:
    ignore_run_exports:
        - blas
        - mkl-service
    number: '0'
    string: py38hfbe908c_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - blas 1.0 mkl
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - cython 0.29.13 py38h0a44026_0
        - intel-openmp 2019.4 233
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - mkl 2019.4 233
        - mkl-devel 2019.4 233
        - mkl-include 2019.4 233
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - mkl >=2019.4,<2020.0a0
        - python >=3.8,<3.9.0a0
        - six
test:
    commands:
        - nosetests -v mkl
    imports:
        - mkl
    requires:
        - nose
about:
    description: 'mkl-service exposes a few functions which are declared in mkl_service.h.

        It''s main purpose is to allow the user to change the number

        of CPU''s MKL is using at runtime.

        '
    dev_url: https://github.com/ContinuumIO/mkl-service
    doc_source_url: https://github.com/ContinuumIO/mkl-service/blob/master/docs/index.rst
    doc_url: https://docs.continuum.io/mkl-service/
    home: https://github.com/ContinuumIO/mkl-service
    license: 3-clause BSD
    license_family: BSD
    license_file: LICENSE.txt
    summary: Python bindings to MKL service functions
extra:
    copy_test_source_files: true
    final: true
