# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/0574425d-cdb3-42e7-5b19-eef0099532ca/volume/rsync-recipes/llvmlite-0.33.0-python_3.8-on-osx, last modified Sun Jul 12 11:53:14 2020
# ------------------------------------------------

package:
    name: llvmlite
    version: 0.33.0
source:
    git_rev: v0.33.0
    git_url: https://github.com/numba/llvmlite
    patches:
        - 0001-link-static.patch
build:
    number: '1'
    script_env:
        - PY_VCRUNTIME_REDIST
    string: py38ha11be7d_1
requirements:
    build:
        - make 4.2.1 h3efe00b_1
    host:
        - ca-certificates 2020.6.24 0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 h1de35cc_1
        - libffi 3.3 hb1e8313_2
        - libllvm9 9.0.1 h21ff451_1
        - llvm-tools 9.0.1 h21ff451_1
        - llvmdev 9.0.1 h21ff451_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcxx >=4.0.1
        - libllvm9 9.0.1 *_1
        - python >=3.8,<3.9.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - python -m llvmlite.tests
    imports:
        - llvmlite
        - llvmlite.binding
about:
    home: https://github.com/numba/llvmlite
    license: New BSD License
    summary: A lightweight LLVM python binding for writing JIT compilers
extra:
    copy_test_source_files: true
    final: true
