# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/eea62505-3611-43d2-71e0-cabd9cf71d9c/volume/rsync-recipes/cffi-1.14.0-python_3.8-on-osx, last modified Thu May  7 18:54:44 2020
# ------------------------------------------------

package:
    name: cffi
    version: 1.14.0
source:
    patches:
        - 0001-Link-to-dl-library.patch
        - setup-linux.patch
    sha256: 2d384f4a127a15ba701207f7639d94106693b6cd64173d6c8988e2c25f3ac2b6
    url: https://pypi.io/packages/source/c/cffi/cffi-1.14.0.tar.gz
build:
    number: '1'
    script: /opt/concourse/worker/volumes/live/eea62505-3611-43d2-71e0-cabd9cf71d9c/volume/cffi_1588898637460/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps -vv
    string: py38hc512035_1
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.0.2 py38_3
        - pycparser 2.20 py_0
        - python 3.8.2 hf48f09d_13
        - readline 8.0 h1de35cc_0
        - setuptools 46.1.3 py38_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - libffi >=3.3,<3.4.0a0
        - pycparser
        - python >=3.8,<3.9.0a0
test:
    commands:
        - pip check
    imports:
        - _cffi_backend
        - cffi
    requires:
        - openssl
        - pip
about:
    description: 'Cffi aims to allow users to call C code from Python without having
        to

        learn a 3rd language. It provides a convenient and reliable way to call

        compiled C code from Python using interface declarations written in C.

        '
    dev_url: https://bitbucket.org/cffi/cffi/overview
    doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
    doc_url: http://cffi.readthedocs.org
    home: https://bitbucket.org/cffi/cffi
    license: MIT
    license_file: LICENSE
    summary: Foreign Function Interface for Python calling C code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - inducer
        - mingwandroid
        - ocefpaf
