# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/cb65dff6-3431-4915-5353-bb37bba1fb64/volume/rsync-recipes/pytest-5.4.3-python_3.8-on-osx, last modified Tue Jun 16 10:54:02 2020
# ------------------------------------------------

package:
    name: pytest
    version: 5.4.3
source:
    sha256: 7979331bfcba207414f5e1263b5a0f8f521d0f457318836a7355531ed1a4c7d8
    url: https://pypi.io/packages/source/p/pytest/pytest-5.4.3.tar.gz
build:
    entry_points:
        - py.test = py.test:main
        - pytest = py.test:main
    number: '0'
    script: /opt/concourse/worker/volumes/live/cb65dff6-3431-4915-5353-bb37bba1fb64/volume/pytest_1592323091362/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        setup.py install --single-version-externally-managed --record record.txt
    string: py38_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.0.2 py38_3
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 47.1.1 py38_0
        - setuptools-scm 3.5.0 py_1
        - setuptools_scm 3.5.0 1
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - attrs >=17.4.0
        - more-itertools >=4.0
        - packaging
        - pluggy >=0.12,<1.0
        - py >=1.5.0
        - python >=3.8,<3.9.0a0
        - setuptools >=40.0
        - wcwidth
    run_constrained:
        - pytest-faulthandler >=2
test:
    commands:
        - pytest -h
    imports:
        - pytest
about:
    description: 'The pytest framework makes it easy to write small tests, yet scales
        to

        support complex functional testing for applications and libraries.

        '
    dev_url: https://github.com/pytest-dev/pytest/
    doc_url: https://docs.pytest.org/en/latest/
    home: https://docs.pytest.org/en/latest/
    license: MIT
    license_file: LICENSE
    summary: Simple and powerful testing with Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - flub
        - goanpeca
        - mingwandroid
        - nicoddemus
        - ocefpaf
