# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/32ef3b19-6d5e-459b-54bf-1bfa312324b4/volume/rsync-recipes/sympy-1.6.1-python_3.8-on-osx, last modified Wed Jul  8 14:27:36 2020
# ------------------------------------------------

package:
    name: sympy
    version: 1.6.1
source:
    sha256: 7386dba4f7e162e90766b5ea7cab5938c2fe3c620b310518c8ff504b283cb15b
    url: https://pypi.io/packages/source/s/sympy/sympy-1.6.1.tar.gz
build:
    entry_points:
        - isympy = isympy:main
    number: '0'
    script: /opt/concourse/worker/volumes/live/32ef3b19-6d5e-459b-54bf-1bfa312324b4/volume/sympy_1594236601710/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_0
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 hb1e8313_2
        - mpmath 1.1.0 py38_0
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_2
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - mpmath >=0.19
        - python >=3.8,<3.9.0a0
    run_constrained:
        - antlr-python-runtime >=4.7,<4.8
test:
    commands:
        - isympy --help
    imports:
        - sympy
about:
    description: 'SymPy is a Python library for symbolic mathematics. It aims to become
        a

        full-featured computer algebra system (CAS) while keeping the code as

        simple as possible in order to be comprehensible and easily extensible.

        '
    dev_url: https://github.com/sympy/sympy
    doc_source_url: https://github.com/sympy/sympy/tree/master/doc
    doc_url: https://docs.sympy.org/latest/index.html
    home: https://sympy.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Python library for symbolic mathematics
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - msarahan
        - scopatz
