# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/83208558-2af4-414c-456f-5e8b625c4ffc/volume/rsync-recipes/msgpack-python-1.0.0-python_3.8-on-osx, last modified Tue Mar 24 14:32:39 2020
# ------------------------------------------------

package:
    name: msgpack-python
    version: 1.0.0
source:
    sha256: 9534d5cc480d4aff720233411a1f765be90885750b07df772380b34c10ecb5c0
    url: https://pypi.io/packages/source/m/msgpack/msgpack-1.0.0.tar.gz
build:
    number: '1'
    script: /opt/concourse/worker/volumes/live/83208558-2af4-414c-456f-5e8b625c4ffc/volume/msgpack-python_1585079204824/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . -vv
    string: py38h04f5b5a_1
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_1
        - cython 0.29.15 py38h0a44026_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.2 h0a44026_0
        - openssl 1.1.1e h1de35cc_0
        - pip 20.0.2 py38_1
        - python 3.8.1 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 46.1.1 py38_0
        - sqlite 3.31.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.34.2 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcxx >=4.0.1
        - python >=3.8,<3.9.0a0
test:
    imports:
        - msgpack
about:
    description: 'MessagePack lets you exchange data among multiple languages like
        JSON.  But

        it is faster and smaller. Small integers are encoded into a single byte and

        typical short strings require only one extra byte in addition to the

        strings themselves.

        '
    dev_url: https://github.com/msgpack/msgpack
    doc_source_url: https://github.com/msgpack/msgpack-python/blob/master/docs/index.rst
    doc_url: http://msgpack-python.readthedocs.io/
    home: http://msgpack.org/
    license: Apache-2.0
    license_family: Apache
    license_file: COPYING
    summary: MessagePack (de)serializer
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carlodri
        - jakirkham
        - ocefpaf
        - pmlandwehr
