# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/72a7d54d-2106-45f2-580c-98824cd3b909/volume/rsync-recipes/pip-20.1.1-python_3.8-on-osx, last modified Tue Jun 16 10:36:36 2020
# ------------------------------------------------

package:
    name: pip
    version: 20.1.1
source:
    patches:
        - 0001-Win32-Fix-Py_DEBUG-determination-in-_derive_abi-in-w.patch
    sha256: 27f8dc29387dd83249e06e681ce087e6061826582198a425085e0bf4c1cf3a55
    url: https://pypi.io/packages/source/p/pip/pip-20.1.1.tar.gz
build:
    disable_pip: true
    entry_points:
        - pip = pip._internal.cli.main:main
        - pip3 = pip._internal.cli.main:main
    number: '1'
    string: py38_1
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.3 h0a44026_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 47.1.1 py38_0
        - sqlite 3.31.1 h5c1f38d_1
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
