# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f2a8edc0-64b5-40f0-5d81-bbd31149cbe1/volume/rsync-recipes/keyring-21.2.1-python_3.8-on-osx, last modified Thu Jun 25 13:24:08 2020
# ------------------------------------------------

package:
    name: keyring
    version: 21.2.1
source:
    sha256: c53e0e5ccde3ad34284a40ce7976b5b3a3d6de70344c3f8ee44364cc340976ec
    url: https://pypi.io/packages/source/k/keyring/keyring-21.2.1.tar.gz
build:
    entry_points:
        - keyring = keyring.cli:main
    number: '0'
    script: /opt/concourse/worker/volumes/live/f2a8edc0-64b5-40f0-5d81-bbd31149cbe1/volume/keyring_1593109772159/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps -vv
    string: py38_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.6.20 py38_0
        - libcxx 10.0.0 1
        - libedit 3.1.20191231 haf1e3a3_0
        - libffi 3.3 h0a44026_1
        - ncurses 6.2 h0a44026_1
        - openssl 1.1.1g h1de35cc_0
        - pip 20.1.1 py38_1
        - python 3.8.3 h26836e1_1
        - readline 8.0 h1de35cc_0
        - setuptools 47.3.1 py38_0
        - setuptools-scm 3.5.0 py_1
        - setuptools_scm 3.5.0 1
        - sqlite 3.32.3 hffcf06c_0
        - tk 8.6.10 hb0a8c7a_0
        - toml 0.10.1 py_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h1de35cc_0
        - zlib 1.2.11 h1de35cc_3
    run:
        - entrypoints
        - python >=3.8,<3.9.0a0
test:
    commands:
        - pip check
        - keyring --help
    imports:
        - keyring
        - keyring.backends
        - keyring.util
    requires:
        - pip
        - pytest >=2.8
        - pytest-runner
        - setuptools_scm >=1.15.0
    source_files:
        - tests/*
about:
    description: 'the python keyring lib provides a easy way to access the system
        keyring

        service from python.  it can be used in any application that needs safe

        password storage.

        '
    doc_source_url: https://github.com/jaraco/keyring/blob/master/readme.rst
    doc_url: https://pypi.org/project/keyring/
    home: https://github.com/jaraco/keyring
    license: Python Software Foundation or MIT
    license_family: MIT
    license_file: LICENSE
    summary: Store and access your passwords safely
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - ericdill
        - licode
        - tacaswell
